# The difference between annotations and original annotations is that in Annotations some things have been cleaned by hand

In [27]:
import sys
sys.path.append('../modules')

import pandas as pd
from sklearn.metrics import cohen_kappa_score,accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from datetime import datetime
import matplotlib.pyplot as plt
import seaborn as sns
from noiseDiscovery import noiseDiscovery
from deleteNotCoerent import deleteNotCoerent
from cleanAndCast import cleanAndCast
from seeDistinctValues import seeDistinctValues


#Leggo il file in output di chatGPT
chatGPTOutpt = pd.read_csv('../Query/output/outputChatGPT_SingleQ1_1_Suggestions.csv')

#Leggo le annotazioni parsate degli annotatori
annotazioni = pd.read_csv('../Annotations/Annotations.csv')

In [28]:
# Rinomino le colonne nel file di annotazioni originali

annotazioni.drop(['url', 'URL(*)', 'Q2.11 Other media', 'Q2.12 News presented type', 'Q2.13 Visual bias'], axis=1, inplace=True)
annotazioni.fillna('', inplace=True)

# Rinomina le colonne utilizzando solo i numeri
annotazioni = annotazioni.rename(columns={
    'Q.1.1 Type of news': 'Q1.1',
    'Q.1.2 Accuracy': 'Q1.2',
    'Q.1.3 Headline': 'Q1.3',
    'Q1.3.1 Quotation': 'Q1.3.1',
    'Q.1.4 Fact-based lead': 'Q1.4',
    'Q.1.5 Bias': 'Q1.5',
    'Q.1.6 Sensational language': 'Q1.6',
    'Q1.7 Negative target': 'Q1.7',
    'Q1.7.1 If the article negatively targets a specific group, please check the types of targeting from the options below': 'Q1.7.1',
    'Q1.7.1.2 Please specify the type': 'Q1.7.1.2',
    'Q2.8 Attribution': 'Q2.8',
    'Q2.9.1 Date': 'Q2.9.1',
    'Q2.9.2 Exact Date': 'Q2.9.2',
    'Q2.10 event 30 days': 'Q2.10'
})

/tmp/ipykernel_63481/3304391576.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  annotazioni.fillna('', inplace=True)

In [29]:
############### CONTROLLO SE CI SONO VALORI STRANI #################
noiseDiscovery(annotazioni)
print('*********************************')
print('*********************************')
print('*********************************')
noiseDiscovery(chatGPTOutpt)

*********************************
*********************************
*********************************
Q1.1 "-1"
Q1.1 "-1"
Q1.2 "-1"
Q1.2 "-1"
Q1.2 "-1"
Q1.2 "-1"
Q1.2 "-1"
Q1.2 "-1"
Q1.2 "-1"
Q1.2 "-1"
Q1.2 "-1"
Q1.2 "-1"
Q1.2 "-1"
Q1.2 "-1"
Q1.2 "-1"
Q1.2 "-1"
Q1.2 "-1"
Q1.2 "-1"
Q1.2 "-1"
Q1.2 "-1"
Q1.2 "-1"
Q1.2 "-1"
Q1.2 "-1"
Q1.2 "-1"
Q1.2 "-1"
Q1.2 "-1"
Q1.2 "-1"
Q1.2 "-1"
Q1.2 "-1"
Q1.2 "-1"
Q1.2 "-1"
Q1.2 "-1"
Q1.2 "-1"
Q1.3.1 "-1"
Q1.3.1 "-1"
Q1.3.1 "-1"
Q1.3.1 "-1"
Q1.3.1 "-1"
Q1.3.1 "-1"
Q1.3.1 "-1"
Q1.3.1 "-1"
Q1.3.1 "-1"
Q1.3.1 "-1"
Q1.3.1 "-1"
Q1.3.1 "-1"
Q1.3.1 "-1"
Q1.3.1 "-1"
Q1.3.1 "-1"
Q1.3.1 "-1"
Q1.3.1 "-1"
Q1.3.1 "-1"
Q1.3.1 "-1"
Q1.3.1 "-1"
Q1.3.1 "-1"
Q1.3.1 "-1"
Q1.3.1 "-1"
Q1.3.1 "-1"
Q1.3.1 "-1"
Q1.3.1 "-1"
Q1.3.1 "-1"
Q1.3.1 "-1"
Q1.3.1 "-1"
Q1.3.1 "-1"
Q1.3.1 "-1"
Q1.4 "-1"
Q1.4 "-1"
Q1.4 "-1"
Q1.4 "-1"
Q1.4 "-1"
Q1.4 "-1"
Q1.4 "-1"
Q1.4 "-1"
Q1.4 "-1"
Q1.4 "-1"
Q1.4 "-1"
Q1.4 "-1"
Q1.4 "-1"
Q1.4 "-1"
Q1.4 "-1"
Q1.4 "-1"
Q1.4 "-1"
Q1.4 "-1"
Q1.4 "-1"
Q1.4 "-1"
Q1.4 "-1"
Q1.4 "-1"
Q1.4 "-1"
Q1.4 "-1"
Q1.4 "-1"
Q1.4 "-1"
Q1.4 "-1"
Q1.4 "-1"
Q1.4 "-1"
Q1.4 "-1"
Q1.4 "-1"
Q1.5 "-1"
Q1.5 "-1"
Q1.5 "-1"
Q1.5 "-1"
Q1.5 "-1"
Q1.5 "-1"
Q1.5 "-1"
Q1.5 "-1"
Q1.5 "-1"
Q1.5 "-1"
Q1.5 "-1"
Q1.5 "-1"
Q1.5 "-1"
Q1.5 "-1"
Q1.5 "-1"
Q1.5 "-1"
Q1.5 "-1"
Q1.5 "-1"
Q1.5 "-1"
Q1.5 "-1"
Q1.5 "-1"
Q1.5 "-1"
Q1.5 "-1"
Q1.5 "-1"
Q1.5 "-1"
Q1.5 "-1"
Q1.5 "-1"
Q1.5 "-1"
Q1.5 "-1"
Q1.5 "-1"
Q1.5 "-1"
Q1.6 "-1"
Q1.6 "-1"
Q1.6 "-1"
Q1.6 "-1"
Q1.6 "-1"
Q1.6 "-1"
Q1.6 "-1"
Q1.6 "-1"
Q1.6 "-1"
Q1.6 "-1"
Q1.6 "-1"
Q1.6 "-1"
Q1.6 "-1"
Q1.6 "-1"
Q1.6 "-1"
Q1.6 "-1"
Q1.6 "-1"
Q1.6 "-1"
Q1.6 "-1"
Q1.6 "-1"
Q1.6 "-1"
Q1.6 "-1"
Q1.6 "-1"
Q1.6 "-1"
Q1.6 "-1"
Q1.6 "-1"
Q1.6 "-1"
Q1.6 "-1"
Q1.6 "-1"
Q1.6 "-1"
Q1.6 "-1"
Q1.7 "-1"
Q1.7 "-1"
Q1.7 "-1"
Q1.7 "-1"
Q1.7 "-1"
Q1.7 "-1"
Q1.7 "-1"
Q1.7 "-1"
Q1.7 "-1"
Q1.7 "-1"
Q1.7 "-1"
Q1.7 "-1"
Q1.7 "-1"
Q1.7 "-1"
Q1.7 "-1"
Q1.7 "-1"
Q1.7 "-1"
Q1.7 "-1"
Q1.7 "-1"
Q1.7 "-1"
Q1.7 "-1"
Q1.7 "-1"
Q1.7 "-1"
Q1.7 "-1"
Q1.7 "-1"
Q1.7 "-1"
Q1.7 "-1"
Q1.7 "-1"
Q1.7 "-1"
Q1.7 "-1"
Q1.7 "-1"

AttributeError: 'int' object has no attribute 'split'

In [30]:
############ CONTROLLO I SINGOLI VALORI DISTINTI PER COLONNA ################
seeDistinctValues(annotazioni)
print('*********************************')
print('*********************************')
print('*********************************')
seeDistinctValues(chatGPTOutpt)

Colonna annotator:
['Manuel' 'Marinella' 'Angelo' 'marinella' '']
Colonna Q1.1:
['1' '' '2' '4' '3' '5']
Colonna Q1.2:
['2' '' '3' '4' '1']
Colonna Q1.3:
['3' '' '1;3' '3;9' '1;3;5' '1;3;4' '1;4' '4;9' '3;4' '1' '9' '1;3;9'
 '1;9' '1;5' '1;2;4' '1;2;3;4' '1;3;8' '1;8' '1;3;4;9' '1;2;3;4;9'
 '1;3;4;7;9' '3;4;9' '1;2' '1;3;5;9' '3;4;8' '7' '2;3' '1;5;9' '4;8' '8'
 '3;8' '3;6' '4' '5' '2' '1;2;9' '1;4;8;9' '1;3;4;5;9' '1;2;3;4;5;9'
 '1;2;8;9' '1;3;8;9' '1;2;4;9' '1;4;9' '1;7;9' '1;8;9']
Colonna Q1.3.1:
['' '1' '2']
Colonna Q1.4:
['2' '' '1']
Colonna Q1.5:
['4' '' '3' '2' '1']
Colonna Q1.6:
['4' '' '2' '3' '1']
Colonna Q1.7:
['1' '' '2']
Colonna Q1.7.1:
['' '11' '3' '12' '0' '1' '6' '2;5' '5' '2' '11;12' '5;11' '2;12' '10'
 '6;7' '7;11' '5;7' '9' '5;12' '10;11' '2;3;4;12' '2;3;4']
Colonna Q1.7.1.2:
['' 'Fashion craft industries system' 'Mass production'
 'Government of Morocco' 'Right-wing' 'AIFA' 'Italian' 'Italians' 'PD'
 'liberals' 'European Union' 'M5S' 'Giunta siciliana' 'Lega;Ostellari'
 'Minister Giovannini' 'Republican party' 'aifa' 'Who commits catcalling'
 'Letta' 'Davigo' 'CSM' 'Davigo; CSM' 'italian government' 'Lukashenko'
 'Judges' 'Biden' 'Letta; Biden; Hamas' 'Simon Levis Sullivan'
 'liberals, Simon levis' 'Defaulting citizens'
 'Politics;virologists;tv-shows' 'Magistrates' 'anti-racism' 'Speranza'
 'Person' 'National singers' 'chauvinists' 'Giuseppe Magliulo' 'Benetton'
 "D'Alema" 'The assassin' 'Figliuolo' 'Cremlin' 'Bolsonaro'
 'part of the judiciary' 'Guards' 'Pharma lobbies' 'shovinism' 'far right'
 'Islam Extremist;Government' 'islam; immigrants'
 'italian minister Lamorgese' 'wwf' 'big pharma;doctors' 'The accused'
 'Immigrants;ong' 'NGOs dealing with immigration' 'Libyan coast guard'
 'Coast Guard' 'Serbia'
 'Rosamaria Sorge, who started the flame with the initial offensive tweet'
 'EU members' 'Renzi;Salvini;Ferragni' 'Right party' 'De Monte' 'Big tech'
 'Beppe Grillo' 'Who organizes vaccination campaigns' 'Omophoby' 'No vax'
 'The aggressor' 'Politicians' ' Conte; Di Maio' 'cts Speranza'
 'Bergoglio' 'CTS' 'Conte; M5S' 'Speranza;Ema' 'Speranza; Cavaleri'
 'Government' 'Confindustria']
Colonna Q2.8:
['1' '' '3' '2']
Colonna Q2.9.1:
['2' '' '1']
Colonna Q2.9.2:
<DatetimeArray>
['2021-05-31 00:00:00',                 'NaT', '2021-05-29 00:00:00',
 '2019-08-09 00:00:00', '2021-05-20 00:00:00', '2021-06-01 00:00:00',
 '2021-06-30 00:00:00', '2021-05-13 00:00:00', '2021-04-30 00:00:00',
 '2021-05-18 00:00:00', '2021-06-03 00:00:00', '2021-05-30 00:00:00',
 '2021-05-09 00:00:00', '2021-05-14 00:00:00', '2021-03-08 00:00:00',
 '2021-05-12 00:00:00', '2021-04-12 00:00:00', '2021-05-08 00:00:00',
 '2020-10-02 00:00:00', '2021-01-14 00:00:00', '2017-11-01 00:00:00',
 '2021-06-04 00:00:00', '2021-01-15 00:00:00', '2021-05-26 00:00:00',
 '2021-05-24 00:00:00', '2021-05-16 00:00:00', '2021-05-23 00:00:00',
 '2021-05-28 00:00:00', '2021-05-11 00:00:00', '2021-04-20 00:00:00',
 '2021-05-27 00:00:00', '2021-04-23 00:00:00', '2021-06-05 00:00:00',
 '2021-05-10 00:00:00', '2021-05-15 00:00:00', '2021-05-25 00:00:00',
 '2021-05-01 00:00:00', '2020-05-31 00:00:00', '2021-01-28 00:00:00',
 '2021-07-02 00:00:00', '1992-05-23 00:00:00', '2020-04-02 00:00:00',
 '2021-01-23 00:00:00', '2021-04-27 00:00:00', '2021-02-13 00:00:00',
 '2021-11-01 00:00:00', '2021-11-14 00:00:00', '2021-07-01 00:00:00',
 '2021-02-09 00:00:00', '2021-07-05 00:00:00', '2021-07-12 00:00:00',
 '2021-04-10 00:00:00', '2021-05-07 00:00:00', '2021-05-05 00:00:00',
 '2021-02-12 00:00:00', '2017-12-01 00:00:00', '2021-02-26 00:00:00',
 '2021-05-21 00:00:00', '2021-06-20 00:00:00', '2021-07-07 00:00:00',
 '2021-06-28 00:00:00', '2021-01-06 00:00:00', '2021-02-01 00:00:00',
 '2021-01-26 00:00:00', '2021-05-17 00:00:00', '2020-04-06 00:00:00',
 '2021-12-01 00:00:00', '2019-12-01 00:00:00', '2021-01-12 00:00:00',
 '2020-06-28 00:00:00', '2021-05-19 00:00:00', '2021-04-22 00:00:00',
 '2021-07-21 00:00:00', '2021-06-25 00:00:00', '2021-06-27 00:00:00',
 '2021-06-29 00:00:00', '2021-07-04 00:00:00', '2021-06-08 00:00:00',
 '2021-07-06 00:00:00', '2021-06-26 00:00:00', '2021-07-03 00:00:00',
 '2021-06-12 00:00:00', '2021-07-08 00:00:00', '2021-07-19 00:00:00',
 '2021-09-15 00:00:00', '2021-06-18 00:00:00', '2021-06-22 00:00:00',
 '2021-06-23 00:00:00', '2021-07-09 00:00:00', '2021-06-21 00:00:00',
 '2021-06-14 00:00:00', '2021-06-11 00:00:00', '2021-08-12 00:00:00',
 '2021-06-13 00:00:00', '2021-06-17 00:00:00']
Length: 95, dtype: datetime64[ns]
Colonna Q2.10:
['2' '' '1']
*********************************
*********************************
*********************************
Colonna annotator:
['ChatGPT4AsAnnotator']
Colonna Q1.1:
['1' '3' None '2']
Colonna Q1.2:
[None]
Colonna Q1.3:
[-1]
Colonna Q1.3.1:
[None]
Colonna Q1.4:
[None]
Colonna Q1.5:
[None]
Colonna Q1.6:
[None]
Colonna Q1.7:
[None]
Colonna Q1.7.1:
[-1]
Colonna Q1.7.1.2:
[-1]
Colonna Q2.8:
[-1]
Colonna Q2.9.1:
[-1]
Colonna Q2.9.2:
[-1]
Colonna Q2.10:
[-1]
Colonna Problem:
[-1. nan]

In [31]:
annotazioni.dtypes

id                   object
title                object
label                object
annotator            object
Q1.1                 object
Q1.2                 object
Q1.3                 object
Q1.3.1               object
Q1.4                 object
Q1.5                 object
Q1.6                 object
Q1.7                 object
Q1.7.1               object
Q1.7.1.2             object
Q2.8                 object
Q2.9.1               object
Q2.9.2       datetime64[ns]
Q2.10                object
dtype: object

In [32]:
chatGPTOutpt.dtypes

id            object
title         object
label         object
annotator     object
Q1.1          object
Q1.2          object
Q1.3           int64
Q1.3.1        object
Q1.4          object
Q1.5          object
Q1.6          object
Q1.7          object
Q1.7.1         int64
Q1.7.1.2       int64
Q2.8           int64
Q2.9.1         int64
Q2.9.2         int64
Q2.10          int64
Problem      float64
dtype: object

In [33]:
########## CASTO I TIPI E PULISCO ##############

annotazioni = cleanAndCast(annotazioni)
chatGPTOutpt = cleanAndCast(chatGPTOutpt)

/home/john/Progetti/ChatGPTAsAnnotator/ChatGPTAsAnnotator/Code/../modules/cleanAndCast.py:29: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.fillna(-1)

In [34]:
############ CONTROLLO I SINGOLI VALORI DISTINTI PER COLONNA ################
seeDistinctValues(annotazioni)
print('*********************************')
print('*********************************')
print('*********************************')
seeDistinctValues(chatGPTOutpt)

Colonna annotator:
['Manuel' 'Marinella' 'Angelo' 'marinella' -1]
Colonna Q1.1:
[ 1 -1  2  4  3  5]
Colonna Q1.2:
[ 2 -1  3  4  1]
Colonna Q1.3.1:
[-1  1  2]
Colonna Q1.4:
[ 2 -1  1]
Colonna Q1.5:
[ 4 -1  3  2  1]
Colonna Q1.6:
[ 4 -1  2  3  1]
Colonna Q1.7:
[ 1 -1  2]
Colonna Q1.7.1.2:
[-1 'Fashion craft industries system' 'Mass production'
 'Government of Morocco' 'Right-wing' 'AIFA' 'Italian' 'Italians' 'PD'
 'liberals' 'European Union' 'M5S' 'Giunta siciliana' 'Lega;Ostellari'
 'Minister Giovannini' 'Republican party' 'aifa' 'Who commits catcalling'
 'Letta' 'Davigo' 'CSM' 'Davigo; CSM' 'italian government' 'Lukashenko'
 'Judges' 'Biden' 'Letta; Biden; Hamas' 'Simon Levis Sullivan'
 'liberals, Simon levis' 'Defaulting citizens'
 'Politics;virologists;tv-shows' 'Magistrates' 'anti-racism' 'Speranza'
 'Person' 'National singers' 'chauvinists' 'Giuseppe Magliulo' 'Benetton'
 "D'Alema" 'The assassin' 'Figliuolo' 'Cremlin' 'Bolsonaro'
 'part of the judiciary' 'Guards' 'Pharma lobbies' 'shovinism' 'far right'
 'Islam Extremist;Government' 'islam; immigrants'
 'italian minister Lamorgese' 'wwf' 'big pharma;doctors' 'The accused'
 'Immigrants;ong' 'NGOs dealing with immigration' 'Libyan coast guard'
 'Coast Guard' 'Serbia'
 'Rosamaria Sorge, who started the flame with the initial offensive tweet'
 'EU members' 'Renzi;Salvini;Ferragni' 'Right party' 'De Monte' 'Big tech'
 'Beppe Grillo' 'Who organizes vaccination campaigns' 'Omophoby' 'No vax'
 'The aggressor' 'Politicians' ' Conte; Di Maio' 'cts Speranza'
 'Bergoglio' 'CTS' 'Conte; M5S' 'Speranza;Ema' 'Speranza; Cavaleri'
 'Government' 'Confindustria']
Colonna Q2.8:
[ 1 -1  3  2]
Colonna Q2.9.1:
[ 2 -1  1]
Colonna Q2.9.2:
<DatetimeArray>
['2021-05-31 00:00:00',                 'NaT', '2021-05-29 00:00:00',
 '2019-08-09 00:00:00', '2021-05-20 00:00:00', '2021-06-01 00:00:00',
 '2021-06-30 00:00:00', '2021-05-13 00:00:00', '2021-04-30 00:00:00',
 '2021-05-18 00:00:00', '2021-06-03 00:00:00', '2021-05-30 00:00:00',
 '2021-05-09 00:00:00', '2021-05-14 00:00:00', '2021-03-08 00:00:00',
 '2021-05-12 00:00:00', '2021-04-12 00:00:00', '2021-05-08 00:00:00',
 '2020-10-02 00:00:00', '2021-01-14 00:00:00', '2017-11-01 00:00:00',
 '2021-06-04 00:00:00', '2021-01-15 00:00:00', '2021-05-26 00:00:00',
 '2021-05-24 00:00:00', '2021-05-16 00:00:00', '2021-05-23 00:00:00',
 '2021-05-28 00:00:00', '2021-05-11 00:00:00', '2021-04-20 00:00:00',
 '2021-05-27 00:00:00', '2021-04-23 00:00:00', '2021-06-05 00:00:00',
 '2021-05-10 00:00:00', '2021-05-15 00:00:00', '2021-05-25 00:00:00',
 '2021-05-01 00:00:00', '2020-05-31 00:00:00', '2021-01-28 00:00:00',
 '2021-07-02 00:00:00', '1992-05-23 00:00:00', '2020-04-02 00:00:00',
 '2021-01-23 00:00:00', '2021-04-27 00:00:00', '2021-02-13 00:00:00',
 '2021-11-01 00:00:00', '2021-11-14 00:00:00', '2021-07-01 00:00:00',
 '2021-02-09 00:00:00', '2021-07-05 00:00:00', '2021-07-12 00:00:00',
 '2021-04-10 00:00:00', '2021-05-07 00:00:00', '2021-05-05 00:00:00',
 '2021-02-12 00:00:00', '2017-12-01 00:00:00', '2021-02-26 00:00:00',
 '2021-05-21 00:00:00', '2021-06-20 00:00:00', '2021-07-07 00:00:00',
 '2021-06-28 00:00:00', '2021-01-06 00:00:00', '2021-02-01 00:00:00',
 '2021-01-26 00:00:00', '2021-05-17 00:00:00', '2020-04-06 00:00:00',
 '2021-12-01 00:00:00', '2019-12-01 00:00:00', '2021-01-12 00:00:00',
 '2020-06-28 00:00:00', '2021-05-19 00:00:00', '2021-04-22 00:00:00',
 '2021-07-21 00:00:00', '2021-06-25 00:00:00', '2021-06-27 00:00:00',
 '2021-06-29 00:00:00', '2021-07-04 00:00:00', '2021-06-08 00:00:00',
 '2021-07-06 00:00:00', '2021-06-26 00:00:00', '2021-07-03 00:00:00',
 '2021-06-12 00:00:00', '2021-07-08 00:00:00', '2021-07-19 00:00:00',
 '2021-09-15 00:00:00', '2021-06-18 00:00:00', '2021-06-22 00:00:00',
 '2021-06-23 00:00:00', '2021-07-09 00:00:00', '2021-06-21 00:00:00',
 '2021-06-14 00:00:00', '2021-06-11 00:00:00', '2021-08-12 00:00:00',
 '2021-06-13 00:00:00', '2021-06-17 00:00:00']
Length: 95, dtype: datetime64[ns]
Colonna Q2.10:
[ 2 -1  1]
Colonna Q1.3_1:
[-1  1]
Colonna Q1.3_2:
[-1  1]
Colonna Q1.3_3:
[ 1 -1]
Colonna Q1.3_4:
[-1  1]
Colonna Q1.3_5:
[-1  1]
Colonna Q1.3_6:
[-1  1]
Colonna Q1.3_7:
[-1  1]
Colonna Q1.3_8:
[-1  1]
Colonna Q1.3_9:
[-1  1]
Colonna Q1.7.1_0:
[-1  1]
Colonna Q1.7.1_1:
[-1  1]
Colonna Q1.7.1_2:
[-1  1]
Colonna Q1.7.1_3:
[-1  1]
Colonna Q1.7.1_4:
[-1  1]
Colonna Q1.7.1_5:
[-1  1]
Colonna Q1.7.1_6:
[-1  1]
Colonna Q1.7.1_7:
[-1  1]
Colonna Q1.7.1_8:
[-1]
Colonna Q1.7.1_9:
[-1  1]
Colonna Q1.7.1_10:
[-1  1]
Colonna Q1.7.1_11:
[-1  1]
Colonna Q1.7.1_12:
[-1  1]
*********************************
*********************************
*********************************
Colonna annotator:
['ChatGPT4AsAnnotator']
Colonna Q1.1:
[ 1  3 -1  2]
Colonna Q1.2:
[-1]
Colonna Q1.3.1:
[-1]
Colonna Q1.4:
[-1]
Colonna Q1.5:
[-1]
Colonna Q1.6:
[-1]
Colonna Q1.7:
[-1]
Colonna Q1.7.1.2:
[-1]
Colonna Q2.8:
[-1]
Colonna Q2.9.1:
[-1]
Colonna Q2.9.2:
<DatetimeArray>
['NaT']
Length: 1, dtype: datetime64[ns]
Colonna Q2.10:
[-1]
Colonna Q1.3_1:
[-1]
Colonna Q1.3_2:
[-1]
Colonna Q1.3_3:
[-1]
Colonna Q1.3_4:
[-1]
Colonna Q1.3_5:
[-1]
Colonna Q1.3_6:
[-1]
Colonna Q1.3_7:
[-1]
Colonna Q1.3_8:
[-1]
Colonna Q1.3_9:
[-1]
Colonna Q1.7.1_0:
[-1]
Colonna Q1.7.1_1:
[-1]
Colonna Q1.7.1_2:
[-1]
Colonna Q1.7.1_3:
[-1]
Colonna Q1.7.1_4:
[-1]
Colonna Q1.7.1_5:
[-1]
Colonna Q1.7.1_6:
[-1]
Colonna Q1.7.1_7:
[-1]
Colonna Q1.7.1_8:
[-1]
Colonna Q1.7.1_9:
[-1]
Colonna Q1.7.1_10:
[-1]
Colonna Q1.7.1_11:
[-1]
Colonna Q1.7.1_12:
[-1]

In [35]:
annotazioni.dtypes

id                   object
title                object
label                object
annotator            object
Q1.1                  int64
Q1.2                  int64
Q1.3.1                int64
Q1.4                  int64
Q1.5                  int64
Q1.6                  int64
Q1.7                  int64
Q1.7.1.2             object
Q2.8                  int64
Q2.9.1                int64
Q2.9.2       datetime64[ns]
Q2.10                 int64
Q1.3_1                int64
Q1.3_2                int64
Q1.3_3                int64
Q1.3_4                int64
Q1.3_5                int64
Q1.3_6                int64
Q1.3_7                int64
Q1.3_8                int64
Q1.3_9                int64
Q1.7.1_0              int64
Q1.7.1_1              int64
Q1.7.1_2              int64
Q1.7.1_3              int64
Q1.7.1_4              int64
Q1.7.1_5              int64
Q1.7.1_6              int64
Q1.7.1_7              int64
Q1.7.1_8              int64
Q1.7.1_9              int64
Q1.7.1_10             int64
Q1.7.1_11             int64
Q1.7.1_12             int64
dtype: object

In [36]:
########## Elimino le righe a cui mancano risposte obbligatorie ##########

annotazioni = deleteNotCoerent(annotazioni)
print('*********************************')
print('*********************************')
print('*********************************')
chatGPTOutpt = deleteNotCoerent(chatGPTOutpt)

Numero di righe rimosse: 389
*********************************
*********************************
*********************************
Numero di righe rimosse: 2

In [37]:
annotazioni.head()

,id,title,label,annotator,Q1.1,Q1.2,Q1.3.1,Q1.4,Q1.5,Q1.6,...,Q1.7.1_3,Q1.7.1_4,Q1.7.1_5,Q1.7.1_6,Q1.7.1_7,Q1.7.1_8,Q1.7.1_9,Q1.7.1_10,Q1.7.1_11,Q1.7.1_12
0,18d71db7-f362-46fa-953e-d8353c7f7232,Coronavirus| nuove regole: al tavolo al ristor...,Group 2,Manuel,1,2,-1,2,4,4,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
2,18d71db7-f362-46fa-953e-d8353c7f7232,Coronavirus| nuove regole: al tavolo al ristor...,Group 2,Angelo,1,3,1,1,4,4,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
3,3ca70f03-38f3-4a7b-bdd3-f012b22e0c7e,Israele: Lapid| ostacoli ma fiducioso su nuovo...,Group 2,Manuel,1,4,-1,2,4,4,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
4,3ca70f03-38f3-4a7b-bdd3-f012b22e0c7e,Israele: Lapid| ostacoli ma fiducioso su nuovo...,Group 2,Marinella,1,4,-1,1,4,4,...,-1,-1,-1,-1,-1,-1,-1,-1,1,-1
6,34b92f4c-32db-454c-a369-ca2032443f6c,Le borsette fatte a 3 euro l'ora vendute a 820...,Group 1,Manuel,2,3,-1,1,3,2,...,-1,-1,-1,-1,-1,-1,-1,-1,1,-1

In [38]:
chatGPTOutpt.head()

,id,title,label,annotator,Q1.1,Q1.2,Q1.3.1,Q1.4,Q1.5,Q1.6,...,Q1.7.1_3,Q1.7.1_4,Q1.7.1_5,Q1.7.1_6,Q1.7.1_7,Q1.7.1_8,Q1.7.1_9,Q1.7.1_10,Q1.7.1_11,Q1.7.1_12
0,3d1ae696-3a3f-43ab-a4ce-61d337a59d7e,"Strage nel Mediterraneo: barcone si ribalta, m...",Group 2,ChatGPT4AsAnnotator,1,-1,-1,-1,-1,-1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
1,7b64542e-11d0-464d-a060-1145a9d0ad3a,"Il premier libico a Roma, dalla ricostruzione ...",Group 2,ChatGPT4AsAnnotator,3,-1,-1,-1,-1,-1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
2,d73018e2-5184-43b7-ba01-e82378666dab,In Fvg trovata la variante Delta in 25 dei 96 ...,Group 2,ChatGPT4AsAnnotator,1,-1,-1,-1,-1,-1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
3,1d134854-568a-4590-86b1-64912b3c3e4d,Nuove aggressioni omofobe a Milano: calci e pu...,Group 2,ChatGPT4AsAnnotator,3,-1,-1,-1,-1,-1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
4,47970d6e-a9e8-4eba-b589-35dc3158d5b3,"Covid, specializzanda del Policlinico di Bari:...",Group 2,ChatGPT4AsAnnotator,3,-1,-1,-1,-1,-1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1

# Unisco e salvo in un unico csv

In [39]:
frames = [annotazioni, chatGPTOutpt]

df = pd.concat(frames)

df.to_csv('merged_checked.csv', encoding='utf-8', index=False)