# The difference between annotations and original annotations is that in Annotations some things have been cleaned by hand

In [1]:
import sys
sys.path.append('../modules')

import pandas as pd
from sklearn.metrics import cohen_kappa_score,accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from datetime import datetime
import matplotlib.pyplot as plt
import seaborn as sns
from noiseDiscovery import noiseDiscovery
from deleteNotCoerent import deleteNotCoerent
from cleanAndCast import cleanAndCast
from seeDistinctValues import seeDistinctValues


#Leggo il file in output di chatGPT
chatGPTOutpt = pd.read_csv('../Query/output/outputChatGPT.csv')

#Leggo le annotazioni parsate degli annotatori
annotazioni = pd.read_csv('../Annotations/Annotations.csv')

In [2]:
# Rinomino le colonne nel file di annotazioni originali

annotazioni.drop(['url', 'URL(*)', 'Q2.11 Other media', 'Q2.12 News presented type', 'Q2.13 Visual bias'], axis=1, inplace=True)
annotazioni.fillna('', inplace=True)

# Rinomina le colonne utilizzando solo i numeri
annotazioni = annotazioni.rename(columns={
    'Q.1.1 Type of news': 'Q1.1',
    'Q.1.2 Accuracy': 'Q1.2',
    'Q.1.3 Headline': 'Q1.3',
    'Q1.3.1 Quotation': 'Q1.3.1',
    'Q.1.4 Fact-based lead': 'Q1.4',
    'Q.1.5 Bias': 'Q1.5',
    'Q.1.6 Sensational language': 'Q1.6',
    'Q1.7 Negative target': 'Q1.7',
    'Q1.7.1 If the article negatively targets a specific group, please check the types of targeting from the options below': 'Q1.7.1',
    'Q1.7.1.2 Please specify the type': 'Q1.7.1.2',
    'Q2.8 Attribution': 'Q2.8',
    'Q2.9.1 Date': 'Q2.9.1',
    'Q2.9.2 Exact Date': 'Q2.9.2',
    'Q2.10 event 30 days': 'Q2.10'
})

/tmp/ipykernel_117990/3304391576.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  annotazioni.fillna('', inplace=True)

In [3]:
############### CONTROLLO SE CI SONO VALORI STRANI #################
noiseDiscovery(annotazioni)
print('*********************************')
print('*********************************')
print('*********************************')
noiseDiscovery(chatGPTOutpt)

*********************************
*********************************
*********************************
Q1.1 "-1"
Q1.1 "-1"
Q1.1 "-1"
Q1.1 "-1"
Q1.1 "-1"
Q1.1 "-1"
Q1.1 "-1"
Q1.1 "-1"
Q1.1 "-1"
Q1.2 "-1"
Q1.2 "-1"
Q1.2 "-1"
Q1.2 "-1"
Q1.2 "-1"
Q1.2 "-1"
Q1.2 "-1"
Q1.2 "-1"
Q1.2 "-1"
Valori non conformi in Q1.3:
-1
-1
-1
-1
-1
-1
-1
-1
-1
Q1.3.1 "-1"
Q1.3.1 "-1"
Q1.3.1 "-1"
Q1.3.1 "-1"
Q1.3.1 "-1"
Q1.3.1 "-1"
Q1.3.1 "-1"
Q1.3.1 "-1"
Q1.3.1 "-1"
Q1.4 "-1"
Q1.4 "-1"
Q1.4 "-1"
Q1.4 "-1"
Q1.4 "-1"
Q1.4 "-1"
Q1.4 "-1"
Q1.4 "-1"
Q1.4 "-1"
Q1.5 "-1"
Q1.5 "-1"
Q1.5 "-1"
Q1.5 "-1"
Q1.5 "-1"
Q1.5 "-1"
Q1.5 "-1"
Q1.5 "-1"
Q1.5 "-1"
Q1.6 "-1"
Q1.6 "-1"
Q1.6 "-1"
Q1.6 "-1"
Q1.6 "-1"
Q1.6 "-1"
Q1.6 "-1"
Q1.6 "-1"
Q1.6 "-1"
Q1.7 "-1"
Q1.7 "-1"
Q1.7 "-1"
Q1.7 "-1"
Q1.7 "-1"
Q1.7 "-1"
Q1.7 "-1"
Q1.7 "-1"
Q1.7 "-1"
Q2.8 "-1"
Q2.8 "-1"
Q2.8 "-1"
Q2.8 "-1"
Q2.8 "-1"
Q2.8 "-1"
Q2.8 "-1"
Q2.8 "-1"
Q2.8 "-1"
Q2.9.1 "-1"
Q2.9.1 "-1"
Q2.9.1 "-1"
Q2.9.1 "-1"
Q2.9.1 "-1"
Q2.9.1 "-1"
Q2.9.1 "-1"
Q2.9.1 "-1"
Q2.9.1 "-1"
Lista di valori di tipo data non coerenti:

 4      Enter the answer in 'DD/MM/YYYY' format
10                                         nan
13     Enter the answer in 'DD/MM/YYYY' format
15     Enter the answer in 'DD/MM/YYYY' format
20                                         nan
                        ...
342                                        nan
343                                Giugno 2021
347                                        nan
348                                        nan
349                                        nan
Name: Q2.9.2, Length: 165, dtype: object
Q2.10 "-1"
Q2.10 "-1"
Q2.10 "-1"
Q2.10 "-1"
Q2.10 "-1"
Q2.10 "-1"
Q2.10 "-1"
Q2.10 "-1"
Q2.10 "-1"

''

In [4]:
############ CONTROLLO I SINGOLI VALORI DISTINTI PER COLONNA ################
seeDistinctValues(annotazioni)
print('*********************************')
print('*********************************')
print('*********************************')
seeDistinctValues(chatGPTOutpt)

Colonna annotator:
['Manuel' 'Marinella' 'Angelo' 'marinella' '']
Colonna Q1.1:
['1' '' '2' '4' '3' '5']
Colonna Q1.2:
['2' '' '3' '4' '1']
Colonna Q1.3:
['3' '' '1;3' '3;9' '1;3;5' '1;3;4' '1;4' '4;9' '3;4' '1' '9' '1;3;9'
 '1;9' '1;5' '1;2;4' '1;2;3;4' '1;3;8' '1;8' '1;3;4;9' '1;2;3;4;9'
 '1;3;4;7;9' '3;4;9' '1;2' '1;3;5;9' '3;4;8' '7' '2;3' '1;5;9' '4;8' '8'
 '3;8' '3;6' '4' '5' '2' '1;2;9' '1;4;8;9' '1;3;4;5;9' '1;2;3;4;5;9'
 '1;2;8;9' '1;3;8;9' '1;2;4;9' '1;4;9' '1;7;9' '1;8;9']
Colonna Q1.3.1:
['' '1' '2']
Colonna Q1.4:
['2' '' '1']
Colonna Q1.5:
['4' '' '3' '2' '1']
Colonna Q1.6:
['4' '' '2' '3' '1']
Colonna Q1.7:
['1' '' '2']
Colonna Q1.7.1:
['' '11' '3' '12' '0' '1' '6' '2;5' '5' '2' '11;12' '5;11' '2;12' '10'
 '6;7' '7;11' '5;7' '9' '5;12' '10;11' '2;3;4;12' '2;3;4']
Colonna Q1.7.1.2:
['' 'Fashion craft industries system' 'Mass production'
 'Government of Morocco' 'Right-wing' 'AIFA' 'Italian' 'Italians' 'PD'
 'liberals' 'European Union' 'M5S' 'Giunta siciliana' 'Lega;Ostellari'
 'Minister Giovannini' 'Republican party' 'aifa' 'Who commits catcalling'
 'Letta' 'Davigo' 'CSM' 'Davigo; CSM' 'italian government' 'Lukashenko'
 'Judges' 'Biden' 'Letta; Biden; Hamas' 'Simon Levis Sullivan'
 'liberals, Simon levis' 'Defaulting citizens'
 'Politics;virologists;tv-shows' 'Magistrates' 'anti-racism' 'Speranza'
 'Person' 'National singers' 'chauvinists' 'Giuseppe Magliulo' 'Benetton'
 "D'Alema" 'The assassin' 'Figliuolo' 'Cremlin' 'Bolsonaro'
 'part of the judiciary' 'Guards' 'Pharma lobbies' 'shovinism' 'far right'
 'Islam Extremist;Government' 'islam; immigrants'
 'italian minister Lamorgese' 'wwf' 'big pharma;doctors' 'The accused'
 'Immigrants;ong' 'NGOs dealing with immigration' 'Libyan coast guard'
 'Coast Guard' 'Serbia'
 'Rosamaria Sorge, who started the flame with the initial offensive tweet'
 'EU members' 'Renzi;Salvini;Ferragni' 'Right party' 'De Monte' 'Big tech'
 'Beppe Grillo' 'Who organizes vaccination campaigns' 'Omophoby' 'No vax'
 'The aggressor' 'Politicians' ' Conte; Di Maio' 'cts Speranza'
 'Bergoglio' 'CTS' 'Conte; M5S' 'Speranza;Ema' 'Speranza; Cavaleri'
 'Government' 'Confindustria']
Colonna Q2.8:
['1' '' '3' '2']
Colonna Q2.9.1:
['2' '' '1']
Colonna Q2.9.2:
<DatetimeArray>
['2021-05-31 00:00:00',                 'NaT', '2021-05-29 00:00:00',
 '2019-08-09 00:00:00', '2021-05-20 00:00:00', '2021-06-01 00:00:00',
 '2021-06-30 00:00:00', '2021-05-13 00:00:00', '2021-04-30 00:00:00',
 '2021-05-18 00:00:00', '2021-06-03 00:00:00', '2021-05-30 00:00:00',
 '2021-05-09 00:00:00', '2021-05-14 00:00:00', '2021-03-08 00:00:00',
 '2021-05-12 00:00:00', '2021-04-12 00:00:00', '2021-05-08 00:00:00',
 '2020-10-02 00:00:00', '2021-01-14 00:00:00', '2017-11-01 00:00:00',
 '2021-06-04 00:00:00', '2021-01-15 00:00:00', '2021-05-26 00:00:00',
 '2021-05-24 00:00:00', '2021-05-16 00:00:00', '2021-05-23 00:00:00',
 '2021-05-28 00:00:00', '2021-05-11 00:00:00', '2021-04-20 00:00:00',
 '2021-05-27 00:00:00', '2021-04-23 00:00:00', '2021-06-05 00:00:00',
 '2021-05-10 00:00:00', '2021-05-15 00:00:00', '2021-05-25 00:00:00',
 '2021-05-01 00:00:00', '2020-05-31 00:00:00', '2021-01-28 00:00:00',
 '2021-07-02 00:00:00', '1992-05-23 00:00:00', '2020-04-02 00:00:00',
 '2021-01-23 00:00:00', '2021-04-27 00:00:00', '2021-02-13 00:00:00',
 '2021-11-01 00:00:00', '2021-11-14 00:00:00', '2021-07-01 00:00:00',
 '2021-02-09 00:00:00', '2021-07-05 00:00:00', '2021-07-12 00:00:00',
 '2021-04-10 00:00:00', '2021-05-07 00:00:00', '2021-05-05 00:00:00',
 '2021-02-12 00:00:00', '2017-12-01 00:00:00', '2021-02-26 00:00:00',
 '2021-05-21 00:00:00', '2021-06-20 00:00:00', '2021-07-07 00:00:00',
 '2021-06-28 00:00:00', '2021-01-06 00:00:00', '2021-02-01 00:00:00',
 '2021-01-26 00:00:00', '2021-05-17 00:00:00', '2020-04-06 00:00:00',
 '2021-12-01 00:00:00', '2019-12-01 00:00:00', '2021-01-12 00:00:00',
 '2020-06-28 00:00:00', '2021-05-19 00:00:00', '2021-04-22 00:00:00',
 '2021-07-21 00:00:00', '2021-06-25 00:00:00', '2021-06-27 00:00:00',
 '2021-06-29 00:00:00', '2021-07-04 00:00:00', '2021-06-08 00:00:00',
 '2021-07-06 00:00:00', '2021-06-26 00:00:00', '2021-07-03 00:00:00',
 '2021-06-12 00:00:00', '2021-07-08 00:00:00', '2021-07-19 00:00:00',
 '2021-09-15 00:00:00', '2021-06-18 00:00:00', '2021-06-22 00:00:00',
 '2021-06-23 00:00:00', '2021-07-09 00:00:00', '2021-06-21 00:00:00',
 '2021-06-14 00:00:00', '2021-06-11 00:00:00', '2021-08-12 00:00:00',
 '2021-06-13 00:00:00', '2021-06-17 00:00:00']
Length: 95, dtype: datetime64[ns]
Colonna Q2.10:
['2' '' '1']
*********************************
*********************************
*********************************
Colonna annotator:
['ChatGPT4AsAnnotator']
Colonna Q1.1:
['1' '3' '2' '5' None]
Colonna Q1.2:
['4' '3' None]
Colonna Q1.3:
["['1']" "['1', '3']" "['1', '4']" "['1', '7']" "['1', '5']" '-1'
 "['1', '3', '8']" "['1', '3', '9']" "['1', '9']" "['1', '8']"
 "['1', '3', '7']"]
Colonna Q1.3.1:
['2' '1' None]
Colonna Q1.4:
['2' None]
Colonna Q1.5:
['4' '3' '2' None '1']
Colonna Q1.6:
['3' '2' '4' None '1']
Colonna Q1.7:
['2' '1' None]
Colonna Q1.7.1:
["['4']" '-1' "['3']" "['10']" '[]' "['9']" "['4', '9']" "['11']"
 "['0', '1']" "['2', '11']" "['0', '10']" "['0', '2', '9']" "['3', '7']"
 "['0', '3', '4', '8', '9']" "['3', '8']" "['3', '9']" "['9', '11']"
 "['10', '11']" "['0', '9']" "['3', '6', '9']" "['6']" "['1', '9']"
 "['0', '3', '9']" "['4', '8']" "['6', '7', '9']" "['0', '11']"]
Colonna Q1.7.1.2:
['Immigrants' '-1' 'LGBTQ' 'Roberto Speranza' nan 'Israelis, Palestinians'
 'Immigrants, Race/ethnicity' 'Giuseppe Conte, Beppe Grillo, Vito Crimi'
 "Massimo D'Alema" 'Russia' 'Women'
 'Francesco Boccia, Matteo Salvini, Giorgia Meloni' 'Rom community'
 'Police officers' 'GiancarloMagalliandAdrianaVolpe' 'Nicola Conficoni'
 'Gender, Reputation (Person)' 'Giuseppe Conte'
 'Fabio e Nicola Riva, Nichi Vendola' 'Matteo Salvini, Ors organization'
 'Querdenken movement, Alternative für Deutschland (AfD) party'
 'LGBTQ, Christians/Christianity' '45-year-old worker' 'RegnoUnito'
 'Radicalized individuals' 'Enrico Montesano' 'Gaza' 'Bosniaks, Serbs'
 'Beppe Grillo, Giuseppe Conte'
 'Roberto Speranza, Mario Draghi, Italians not fully vaccinated, experts like Crisanti'
 'Sicilian Regional Government'
 'LGBTQ, Individuals involved in the incident' 'Palestinians'
 'Somali migrants' 'Saman Abbas and her family' 'Emanuele Burgio'
 'victims of sexual abuse in sports'
 'Enrico Letta, Pd (Democratic Party) members and supporters'
 'Commissario Straordinario, Direttore Generale, Direttore Amministrativo dell’Asp di Reggio Calabria, assessore regionale pro tempore'
 'LGBT community, individuals mentioned in the report' 'Jair Bolsonaro'
 'Due operatrici socio sanitarie' 'Matteo Renzi'
 'Professor Simon Levis Sullivan'
 'Presidenza del Consiglio, Ministero della Salute, Regione Lombardia'
 'Amato De Monte' 'FrancescaBenevento' 'Islam/Muslims'
 'Stasi-Unterlagen-Behörde, Alternative für Deutschland (AfD), Die Linke'
 'Conservatives, Race/ethnicity' 'LGBTQ, Religion (Other), Race/ethnicity'
 'Juventus, Real Madrid, Barcelona' 'Lega (political party)'
 'RobertoSperanza'
 'Vito Crimi, Beppe Grillo, Luigi Di Maio, Davide Crippa, Giuseppe Conte'
 'Aurora Leone' 'Liberals, Race/ethnicity' 'Nichi Vendola'
 'Palestinians, Israelis' 'Conservatives, Gender, Race/ethnicity'
 'Agenzia Italiana del Farmaco (AIFA)' 'CasaPound, Immigrants'
 'Immigrants, Religion (Other)'
 'Hamza C., attivista del centri sociali di origini magrebine'
 'Israel, Palestinians' 'Matteo Renzi, Matteo Salvini, Italia Viva'
 'Palestinians and Israelis'
 'Luigi Di Maio, Movimento 5 Stelle, Simone Uggetti, Federica Guidi, Maria Elena Boschi, Claudio De Vincenti, Raffaella Paita, Stefano Graziano'
 'Shahid Masih' 'Forza Italia, Lega, Fratelli d’Italia, Andrea Ostellari'
 "Lega and Fratelli d'Italia voters" 'Silvia, a 19-year-old girl'
 'Migranti' 'Stefano Fassina, Mino Taricco'
 'Enrico Letta, Partito Democratico, Movimento 5 Stelle, Virginia Raggi, Roberto Gualtieri, Carlo Calenda, Matteo Renzi'
 'Governments and institutions' 'Pelletteria Serena di Poggio a Caiano']
Colonna Q2.8:
['3' '1' None]
Colonna Q2.9.1:
['2' '1' None]
Colonna Q2.9.2:
['03/07/2021' '24/12/2023' '12/06/2021' '29/06/2021'
 "Enter the answer in 'DD/MM/YYYY' format" '20/06/2022' '01/07/2021'
 '22/01/2020' '14/05/2020' '18/05/2021' 'nan' '05/07/2021' '23/05/2019'
 '03/02/2020' '31/05/2021' '12/08/2021' '28/06/2020' '22/05/2021'
 '14/05/2021' '28/05/2021' '-1' '30/05/2021' '27/05/2021' '08/04/2021'
 '31/07/2021' '26/02/2021' '13/05/2021' '06/04/2020' '23/05/2021'
 '07/07/2020' '06/07/2021' '08/07/2021' '19/07/YYYY' '05/07/2023'
 '04/07/2021' '29/05/YYYY' '14/09/2015' '16/05/2021' '01/12/2017'
 '17/04/2021' '18/04/2020' '21/06/2021' '29/05/2021' '11/2022'
 '26/06/YYYY' '18/03/2021' '25/05/2021' '17/05/YYYY' '11/06/2021'
 '30/06/2020' '30/06/2021' '14/08/2018' '22/04/YYYY' '26/06/2021'
 '14/01/2021' '15/06/2021' '18/05/YYYY' '23/01/2021' '30/11/2021'
 '02/07/2021' '31/05/1991' '30/09/2020' '12/05/2023' '06/05/2021'
 '07/07/2021' '24/05/2023' '25/04/2021' '03/2020' '22/12/2018'
 '28/02/2021' '16/07/2019' '17/06/2021' '22/06/2021' '28/01/2021'
 '01/07/2020 - 31/03/2021' '21/05/2021' '21/04/2021' '27/07/2019'
 '24/05/2021' '20/08/2006' '17/05/2021' '01/07/YYYY' '30/03/1921'
 '25/05/2023' '29/04/2021' '12/05/2021' '24/01/2021' '28/06/2021'
 '29/01/2021' '01/04/2021' '16/06/2021' '04/06/2021' '14/05/YYYY'
 '19/03/2020' '12/2019' '14/06/2021' '23/06/2021' '17/07/2019'
 '13/07/2021' '20/06/2021' '05/06/2021' '11/05/2021' '14/11/2021'
 '23/04/2021' '05/05/2021' 'Giugno 2021' '01/02/2021']
Colonna Q2.10:
['2' '1' None]
Colonna Problem:
[-1. nan]

In [5]:
annotazioni.dtypes

id                   object
title                object
label                object
annotator            object
Q1.1                 object
Q1.2                 object
Q1.3                 object
Q1.3.1               object
Q1.4                 object
Q1.5                 object
Q1.6                 object
Q1.7                 object
Q1.7.1               object
Q1.7.1.2             object
Q2.8                 object
Q2.9.1               object
Q2.9.2       datetime64[ns]
Q2.10                object
dtype: object

In [6]:
chatGPTOutpt.dtypes

id            object
title         object
label         object
annotator     object
Q1.1          object
Q1.2          object
Q1.3          object
Q1.3.1        object
Q1.4          object
Q1.5          object
Q1.6          object
Q1.7          object
Q1.7.1        object
Q1.7.1.2      object
Q2.8          object
Q2.9.1        object
Q2.9.2        object
Q2.10         object
Problem      float64
dtype: object

In [7]:
########## CASTO I TIPI E PULISCO ##############

annotazioni = cleanAndCast(annotazioni)
chatGPTOutpt = cleanAndCast(chatGPTOutpt)

In [8]:
############ CONTROLLO I SINGOLI VALORI DISTINTI PER COLONNA ################

seeDistinctValues(annotazioni)
print('*********************************')
print('*********************************')
print('*********************************')
seeDistinctValues(chatGPTOutpt)

Colonna annotator:
['Manuel' 'Marinella' 'Angelo' 'marinella' -1]
Colonna Q1.1:
[ 1 -1  2  4  3  5]
Colonna Q1.2:
[ 2 -1  3  4  1]
Colonna Q1.3:
[31  0 10 37 15 11 20 40 32  1 44 19 28 23  6  3 17 26 14  5 13 34  2 16
 33 42 30 24 39 43 36 35 38 41 29  9 21 12  4  8 18  7 22 25 27]
Colonna Q1.3.1:
[-1  1  2]
Colonna Q1.4:
[ 2 -1  1]
Colonna Q1.5:
[ 4 -1  3  2  1]
Colonna Q1.6:
[ 4 -1  2  3  1]
Colonna Q1.7:
[ 1 -1  2]
Colonna Q1.7.1:
[ 0  5 13  7  1  2 18 12 14  8  6 15  9  3 19 20 17 21 16  4 11 10]
Colonna Q1.7.1.2:
[-1 'Fashion craft industries system' 'Mass production'
 'Government of Morocco' 'Right-wing' 'AIFA' 'Italian' 'Italians' 'PD'
 'liberals' 'European Union' 'M5S' 'Giunta siciliana' 'Lega;Ostellari'
 'Minister Giovannini' 'Republican party' 'aifa' 'Who commits catcalling'
 'Letta' 'Davigo' 'CSM' 'Davigo; CSM' 'italian government' 'Lukashenko'
 'Judges' 'Biden' 'Letta; Biden; Hamas' 'Simon Levis Sullivan'
 'liberals, Simon levis' 'Defaulting citizens'
 'Politics;virologists;tv-shows' 'Magistrates' 'anti-racism' 'Speranza'
 'Person' 'National singers' 'chauvinists' 'Giuseppe Magliulo' 'Benetton'
 "D'Alema" 'The assassin' 'Figliuolo' 'Cremlin' 'Bolsonaro'
 'part of the judiciary' 'Guards' 'Pharma lobbies' 'shovinism' 'far right'
 'Islam Extremist;Government' 'islam; immigrants'
 'italian minister Lamorgese' 'wwf' 'big pharma;doctors' 'The accused'
 'Immigrants;ong' 'NGOs dealing with immigration' 'Libyan coast guard'
 'Coast Guard' 'Serbia'
 'Rosamaria Sorge, who started the flame with the initial offensive tweet'
 'EU members' 'Renzi;Salvini;Ferragni' 'Right party' 'De Monte' 'Big tech'
 'Beppe Grillo' 'Who organizes vaccination campaigns' 'Omophoby' 'No vax'
 'The aggressor' 'Politicians' ' Conte; Di Maio' 'cts Speranza'
 'Bergoglio' 'CTS' 'Conte; M5S' 'Speranza;Ema' 'Speranza; Cavaleri'
 'Government' 'Confindustria']
Colonna Q2.8:
[ 1 -1  3  2]
Colonna Q2.9.1:
[ 2 -1  1]
Colonna Q2.9.2:
<DatetimeArray>
['2021-05-31 00:00:00',                 'NaT', '2021-05-29 00:00:00',
 '2019-08-09 00:00:00', '2021-05-20 00:00:00', '2021-06-01 00:00:00',
 '2021-06-30 00:00:00', '2021-05-13 00:00:00', '2021-04-30 00:00:00',
 '2021-05-18 00:00:00', '2021-06-03 00:00:00', '2021-05-30 00:00:00',
 '2021-05-09 00:00:00', '2021-05-14 00:00:00', '2021-03-08 00:00:00',
 '2021-05-12 00:00:00', '2021-04-12 00:00:00', '2021-05-08 00:00:00',
 '2020-10-02 00:00:00', '2021-01-14 00:00:00', '2017-11-01 00:00:00',
 '2021-06-04 00:00:00', '2021-01-15 00:00:00', '2021-05-26 00:00:00',
 '2021-05-24 00:00:00', '2021-05-16 00:00:00', '2021-05-23 00:00:00',
 '2021-05-28 00:00:00', '2021-05-11 00:00:00', '2021-04-20 00:00:00',
 '2021-05-27 00:00:00', '2021-04-23 00:00:00', '2021-06-05 00:00:00',
 '2021-05-10 00:00:00', '2021-05-15 00:00:00', '2021-05-25 00:00:00',
 '2021-05-01 00:00:00', '2020-05-31 00:00:00', '2021-01-28 00:00:00',
 '2021-07-02 00:00:00', '1992-05-23 00:00:00', '2020-04-02 00:00:00',
 '2021-01-23 00:00:00', '2021-04-27 00:00:00', '2021-02-13 00:00:00',
 '2021-11-01 00:00:00', '2021-11-14 00:00:00', '2021-07-01 00:00:00',
 '2021-02-09 00:00:00', '2021-07-05 00:00:00', '2021-07-12 00:00:00',
 '2021-04-10 00:00:00', '2021-05-07 00:00:00', '2021-05-05 00:00:00',
 '2021-02-12 00:00:00', '2017-12-01 00:00:00', '2021-02-26 00:00:00',
 '2021-05-21 00:00:00', '2021-06-20 00:00:00', '2021-07-07 00:00:00',
 '2021-06-28 00:00:00', '2021-01-06 00:00:00', '2021-02-01 00:00:00',
 '2021-01-26 00:00:00', '2021-05-17 00:00:00', '2020-04-06 00:00:00',
 '2021-12-01 00:00:00', '2019-12-01 00:00:00', '2021-01-12 00:00:00',
 '2020-06-28 00:00:00', '2021-05-19 00:00:00', '2021-04-22 00:00:00',
 '2021-07-21 00:00:00', '2021-06-25 00:00:00', '2021-06-27 00:00:00',
 '2021-06-29 00:00:00', '2021-07-04 00:00:00', '2021-06-08 00:00:00',
 '2021-07-06 00:00:00', '2021-06-26 00:00:00', '2021-07-03 00:00:00',
 '2021-06-12 00:00:00', '2021-07-08 00:00:00', '2021-07-19 00:00:00',
 '2021-09-15 00:00:00', '2021-06-18 00:00:00', '2021-06-22 00:00:00',
 '2021-06-23 00:00:00', '2021-07-09 00:00:00', '2021-06-21 00:00:00',
 '2021-06-14 00:00:00', '2021-06-11 00:00:00', '2021-08-12 00:00:00',
 '2021-06-13 00:00:00', '2021-06-17 00:00:00']
Length: 95, dtype: datetime64[ns]
Colonna Q2.10:
[ 2 -1  1]
*********************************
*********************************
*********************************
Colonna annotator:
['ChatGPT4AsAnnotator']
Colonna Q1.1:
[ 1  3  2  5 -1]
Colonna Q1.2:
[ 4  3 -1]
Colonna Q1.3:
[ 1  2  6  8  7  0  4  5 10  9  3]
Colonna Q1.3.1:
[ 2  1 -1]
Colonna Q1.4:
[ 2 -1]
Colonna Q1.5:
[ 4  3  2 -1  1]
Colonna Q1.6:
[ 3  2  4 -1  1]
Colonna Q1.7:
[ 2  1 -1]
Colonna Q1.7.1:
[19  1 14  9  0 24 21 11  2 13  3  5 16  6 17 18 25 10  8 15 22 12  7 20
 23  4]
Colonna Q1.7.1.2:
['Immigrants' '-1' 'LGBTQ' 'Roberto Speranza' -1 'Israelis, Palestinians'
 'Immigrants, Race/ethnicity' 'Giuseppe Conte, Beppe Grillo, Vito Crimi'
 "Massimo D'Alema" 'Russia' 'Women'
 'Francesco Boccia, Matteo Salvini, Giorgia Meloni' 'Rom community'
 'Police officers' 'GiancarloMagalliandAdrianaVolpe' 'Nicola Conficoni'
 'Gender, Reputation (Person)' 'Giuseppe Conte'
 'Fabio e Nicola Riva, Nichi Vendola' 'Matteo Salvini, Ors organization'
 'Querdenken movement, Alternative für Deutschland (AfD) party'
 'LGBTQ, Christians/Christianity' '45-year-old worker' 'RegnoUnito'
 'Radicalized individuals' 'Enrico Montesano' 'Gaza' 'Bosniaks, Serbs'
 'Beppe Grillo, Giuseppe Conte'
 'Roberto Speranza, Mario Draghi, Italians not fully vaccinated, experts like Crisanti'
 'Sicilian Regional Government'
 'LGBTQ, Individuals involved in the incident' 'Palestinians'
 'Somali migrants' 'Saman Abbas and her family' 'Emanuele Burgio'
 'victims of sexual abuse in sports'
 'Enrico Letta, Pd (Democratic Party) members and supporters'
 'Commissario Straordinario, Direttore Generale, Direttore Amministrativo dell’Asp di Reggio Calabria, assessore regionale pro tempore'
 'LGBT community, individuals mentioned in the report' 'Jair Bolsonaro'
 'Due operatrici socio sanitarie' 'Matteo Renzi'
 'Professor Simon Levis Sullivan'
 'Presidenza del Consiglio, Ministero della Salute, Regione Lombardia'
 'Amato De Monte' 'FrancescaBenevento' 'Islam/Muslims'
 'Stasi-Unterlagen-Behörde, Alternative für Deutschland (AfD), Die Linke'
 'Conservatives, Race/ethnicity' 'LGBTQ, Religion (Other), Race/ethnicity'
 'Juventus, Real Madrid, Barcelona' 'Lega (political party)'
 'RobertoSperanza'
 'Vito Crimi, Beppe Grillo, Luigi Di Maio, Davide Crippa, Giuseppe Conte'
 'Aurora Leone' 'Liberals, Race/ethnicity' 'Nichi Vendola'
 'Palestinians, Israelis' 'Conservatives, Gender, Race/ethnicity'
 'Agenzia Italiana del Farmaco (AIFA)' 'CasaPound, Immigrants'
 'Immigrants, Religion (Other)'
 'Hamza C., attivista del centri sociali di origini magrebine'
 'Israel, Palestinians' 'Matteo Renzi, Matteo Salvini, Italia Viva'
 'Palestinians and Israelis'
 'Luigi Di Maio, Movimento 5 Stelle, Simone Uggetti, Federica Guidi, Maria Elena Boschi, Claudio De Vincenti, Raffaella Paita, Stefano Graziano'
 'Shahid Masih' 'Forza Italia, Lega, Fratelli d’Italia, Andrea Ostellari'
 "Lega and Fratelli d'Italia voters" 'Silvia, a 19-year-old girl'
 'Migranti' 'Stefano Fassina, Mino Taricco'
 'Enrico Letta, Partito Democratico, Movimento 5 Stelle, Virginia Raggi, Roberto Gualtieri, Carlo Calenda, Matteo Renzi'
 'Governments and institutions' 'Pelletteria Serena di Poggio a Caiano']
Colonna Q2.8:
[ 3  1 -1]
Colonna Q2.9.1:
[ 2  1 -1]
Colonna Q2.9.2:
<DatetimeArray>
['2021-07-03 00:00:00', '2023-12-24 00:00:00', '2021-06-12 00:00:00',
 '2021-06-29 00:00:00',                 'NaT', '2022-06-20 00:00:00',
 '2021-07-01 00:00:00', '2020-01-22 00:00:00', '2020-05-14 00:00:00',
 '2021-05-18 00:00:00', '2021-07-05 00:00:00', '2019-05-23 00:00:00',
 '2020-02-03 00:00:00', '2021-05-31 00:00:00', '2021-08-12 00:00:00',
 '2020-06-28 00:00:00', '2021-05-22 00:00:00', '2021-05-14 00:00:00',
 '2021-05-28 00:00:00', '2021-05-30 00:00:00', '2021-05-27 00:00:00',
 '2021-04-08 00:00:00', '2021-07-31 00:00:00', '2021-02-26 00:00:00',
 '2021-05-13 00:00:00', '2020-04-06 00:00:00', '2021-05-23 00:00:00',
 '2020-07-07 00:00:00', '2021-07-06 00:00:00', '2021-07-08 00:00:00',
 '2023-07-05 00:00:00', '2021-07-04 00:00:00', '2015-09-14 00:00:00',
 '2021-05-16 00:00:00', '2017-12-01 00:00:00', '2021-04-17 00:00:00',
 '2020-04-18 00:00:00', '2021-06-21 00:00:00', '2021-05-29 00:00:00',
 '2021-03-18 00:00:00', '2021-05-25 00:00:00', '2021-06-11 00:00:00',
 '2020-06-30 00:00:00', '2021-06-30 00:00:00', '2018-08-14 00:00:00',
 '2021-06-26 00:00:00', '2021-01-14 00:00:00', '2021-06-15 00:00:00',
 '2021-01-23 00:00:00', '2021-11-30 00:00:00', '2021-07-02 00:00:00',
 '1991-05-31 00:00:00', '2020-09-30 00:00:00', '2023-05-12 00:00:00',
 '2021-05-06 00:00:00', '2021-07-07 00:00:00', '2023-05-24 00:00:00',
 '2021-04-25 00:00:00', '2018-12-22 00:00:00', '2021-02-28 00:00:00',
 '2019-07-16 00:00:00', '2021-06-17 00:00:00', '2021-06-22 00:00:00',
 '2021-01-28 00:00:00', '2021-05-21 00:00:00', '2021-04-21 00:00:00',
 '2019-07-27 00:00:00', '2021-05-24 00:00:00', '2006-08-20 00:00:00',
 '2021-05-17 00:00:00', '1921-03-30 00:00:00', '2023-05-25 00:00:00',
 '2021-04-29 00:00:00', '2021-05-12 00:00:00', '2021-01-24 00:00:00',
 '2021-06-28 00:00:00', '2021-01-29 00:00:00', '2021-04-01 00:00:00',
 '2021-06-16 00:00:00', '2021-06-04 00:00:00', '2020-03-19 00:00:00',
 '2021-06-14 00:00:00', '2021-06-23 00:00:00', '2019-07-17 00:00:00',
 '2021-07-13 00:00:00', '2021-06-20 00:00:00', '2021-06-05 00:00:00',
 '2021-05-11 00:00:00', '2021-11-14 00:00:00', '2021-04-23 00:00:00',
 '2021-05-05 00:00:00', '2021-02-01 00:00:00']
Length: 92, dtype: datetime64[ns]
Colonna Q2.10:
[ 2  1 -1]

In [9]:
annotazioni.dtypes

id                   object
title                object
label                object
annotator            object
Q1.1                  int64
Q1.2                  int64
Q1.3                  int64
Q1.3.1                int64
Q1.4                  int64
Q1.5                  int64
Q1.6                  int64
Q1.7                  int64
Q1.7.1                int64
Q1.7.1.2             object
Q2.8                  int64
Q2.9.1                int64
Q2.9.2       datetime64[ns]
Q2.10                 int64
dtype: object

In [10]:
########## Elimino le righe a cui mancano risposte obbligatorie ##########

annotazioni = deleteNotCoerent(annotazioni, 'AnnotatoriUmani')
print('*********************************')
chatGPTOutpt = deleteNotCoerent(chatGPTOutpt, 'ChatGPT')

Numero di righe con tutti valori impostati a -1 (mancanti) per AnnotatoriUmani: 389
Numero di righe con almeno un valore mancante nei campi obbligatori per AnnotatoriUmani: 33
*********************************
Numero di righe con tutti valori impostati a -1 (mancanti) per ChatGPT: 9
Non ci sono righe con almeno un valore mancante nei campi obbligatori per ChatGPT

/home/john/Progetti/ChatGPTAsAnnotator/ChatGPTAsAnnotator/Code/../modules/deleteNotCoerent.py:46: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~all_negative_one]
/home/john/Progetti/ChatGPTAsAnnotator/ChatGPTAsAnnotator/Code/../modules/deleteNotCoerent.py:46: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~all_negative_one]

In [11]:
annotazioni.head()

,id,title,label,annotator,Q1.1,Q1.2,Q1.3,Q1.3.1,Q1.4,Q1.5,Q1.6,Q1.7,Q1.7.1,Q1.7.1.2,Q2.8,Q2.9.1,Q2.9.2,Q2.10
0,18d71db7-f362-46fa-953e-d8353c7f7232,Coronavirus| nuove regole: al tavolo al ristor...,Group 2,Manuel,1,2,31,-1,2,4,4,1,0,-1,1,2,2021-05-31,2
2,18d71db7-f362-46fa-953e-d8353c7f7232,Coronavirus| nuove regole: al tavolo al ristor...,Group 2,Angelo,1,3,10,1,1,4,4,1,0,-1,1,2,2021-05-31,2
3,3ca70f03-38f3-4a7b-bdd3-f012b22e0c7e,Israele: Lapid| ostacoli ma fiducioso su nuovo...,Group 2,Manuel,1,4,10,-1,2,4,4,1,0,-1,3,2,2021-05-31,2
4,3ca70f03-38f3-4a7b-bdd3-f012b22e0c7e,Israele: Lapid| ostacoli ma fiducioso su nuovo...,Group 2,Marinella,1,4,10,-1,1,4,4,2,5,-1,3,2,2021-05-31,2
6,34b92f4c-32db-454c-a369-ca2032443f6c,Le borsette fatte a 3 euro l'ora vendute a 820...,Group 1,Manuel,2,3,31,-1,1,3,2,2,5,Fashion craft industries system,3,1,NaT,1

In [12]:
chatGPTOutpt.head()

,id,title,label,annotator,Q1.1,Q1.2,Q1.3,Q1.3.1,Q1.4,Q1.5,Q1.6,Q1.7,Q1.7.1,Q1.7.1.2,Q2.8,Q2.9.1,Q2.9.2,Q2.10
0,3d1ae696-3a3f-43ab-a4ce-61d337a59d7e,"Strage nel Mediterraneo: barcone si ribalta, m...",Group 2,ChatGPT4AsAnnotator,1,4,1,2,2,4,3,2,19,Immigrants,3,2,2021-07-03,2
1,7b64542e-11d0-464d-a060-1145a9d0ad3a,"Il premier libico a Roma, dalla ricostruzione ...",Group 2,ChatGPT4AsAnnotator,3,4,2,2,2,4,3,1,1,-1,3,2,2023-12-24,2
2,d73018e2-5184-43b7-ba01-e82378666dab,In Fvg trovata la variante Delta in 25 dei 96 ...,Group 2,ChatGPT4AsAnnotator,1,4,1,2,2,4,3,1,1,-1,3,2,2021-06-12,2
3,1d134854-568a-4590-86b1-64912b3c3e4d,Nuove aggressioni omofobe a Milano: calci e pu...,Group 2,ChatGPT4AsAnnotator,3,4,1,2,2,3,2,2,14,LGBTQ,3,2,2021-06-29,1
4,47970d6e-a9e8-4eba-b589-35dc3158d5b3,"Covid, specializzanda del Policlinico di Bari:...",Group 2,ChatGPT4AsAnnotator,3,4,1,2,2,4,4,1,1,-1,3,2,NaT,2

# Unisco e salvo in un unico csv

In [13]:
frames = [annotazioni, chatGPTOutpt]

df = pd.concat(frames)

df.to_csv('merged_checked.csv', encoding='utf-8', index=False)