In [35]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import cohen_kappa_score

le = LabelEncoder()


df = pd.read_csv('../Annotations/Annotations_checked.csv')

# Faccio label encoding di Headline

df['Q1.3'] = le.fit_transform(df['Q1.3'])

df['Q1.7.1'] = le.fit_transform(df['Q1.7.1'])
df

,id,title,label,annotator,Q1.1,Q1.2,Q1.3,Q1.3.1,Q1.4,Q1.5,Q1.6,Q1.7,Q1.7.1,Q1.7.1.2,Q2.8,Q2.9.1,Q2.9.2,Q2.10
0,18d71db7-f362-46fa-953e-d8353c7f7232,Coronavirus| nuove regole: al tavolo al ristor...,Group 2,Manuel,1,2,37,0,2,4,4,1,0,NaN,0,0,2021-05-31,2
1,18d71db7-f362-46fa-953e-d8353c7f7232,Coronavirus| nuove regole: al tavolo al ristor...,Group 2,Angelo,1,3,18,1,1,4,4,1,0,NaN,0,0,2021-05-31,2
2,3ca70f03-38f3-4a7b-bdd3-f012b22e0c7e,Israele: Lapid| ostacoli ma fiducioso su nuovo...,Group 2,Manuel,1,4,18,0,2,4,4,1,0,NaN,0,0,2021-05-31,2
3,3ca70f03-38f3-4a7b-bdd3-f012b22e0c7e,Israele: Lapid| ostacoli ma fiducioso su nuovo...,Group 2,Marinella,1,4,18,0,1,4,4,2,6,NaN,0,0,2021-05-31,2
4,34b92f4c-32db-454c-a369-ca2032443f6c,Le borsette fatte a 3 euro l'ora vendute a 820...,Group 1,Manuel,2,3,37,0,1,3,2,2,6,Fashion craft industries system,0,0,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
666,ec3a0585-9da6-4732-bf58-c6e659d8e58e,La grande ondata di caldo nel Nord America,Group 1,Angelo,1,3,27,1,2,3,4,1,0,NaN,0,0,2021-06-30,2
667,5b30e244-4aa2-4ad3-b24a-2022c1415df7,Cosa fare dei documenti della Stasi,Group 1,Marinella,3,3,26,0,1,4,4,1,0,NaN,0,0,2021-06-17,2
668,5b30e244-4aa2-4ad3-b24a-2022c1415df8,Cosa fare dei documenti della Stasi,Group 1,Angelo,3,3,27,0,2,4,4,1,0,NaN,0,0,2021-06-17,2
669,eab45a62-1d47-4216-a51d-e45ccbcc3810,"Strani dolori allo stomaco, dopo 6 mesi muore ...",Group 1,Marinella,1,4,27,0,1,4,3,1,0,NaN,0,0,2021-06-25,2
670,eab45a62-1d47-4216-a51d-e45ccbcc3810,"Strani dolori allo stomaco, dopo 6 mesi muore ...",Group 1,Angelo,5,4,27,0,2,4,3,1,0,NaN,0,0,2021-06-25,2

In [37]:
from sklearn.metrics import cohen_kappa_score
from datetime import datetime

# Per ciascun articolo condiviso, calcola il coefficiente Kappa di Cohen
def getKappa (annotator_1, annotator_2):
# Inizializza una lista per memorizzare i coefficienti Kappa di Cohen
    kappa_scores = []

    articles = set(df[df['annotator'] == annotator_1]['id']).intersection(
    set(df[df['annotator'] == annotator_2]['id']))
    for article_id in articles:
        annotator1 = df[(df['id'] == article_id) & (df['annotator'] == annotator_1)][['Q1.1', 'Q1.2', 'Q1.3', 'Q1.3.1', 'Q1.4', 'Q1.5', 'Q1.6', 'Q1.7','Q1.7.1', 'Q2.8', 'Q2.9.1', 'Q2.9.2', 'Q2.10']]
        annotator2 = df[(df['id'] == article_id) & (df['annotator'] == annotator_2)][['Q1.1', 'Q1.2', 'Q1.3', 'Q1.3.1', 'Q1.4', 'Q1.5', 'Q1.6', 'Q1.7','Q1.7.1', 'Q2.8', 'Q2.9.1', 'Q2.9.2', 'Q2.10']]

        annotator1['Q2.9.2'] = pd.to_datetime(annotator1['Q2.9.2'])
        annotator2['Q2.9.2'] = pd.to_datetime(annotator2['Q2.9.2'])

        annotator1['Q2.9.2'] = annotator1['Q2.9.2'].astype('int64')
        annotator2['Q2.9.2'] = annotator2['Q2.9.2'].astype('int64')

        # Converti i valori in numeri interi o float
        annotator1 = annotator1.astype(float)
        annotator2 = annotator2.astype(float)
        
        # Calcola il coefficiente Kappa di Cohen per ciascuna coppia di annotatori
        k = cohen_kappa_score(annotator1.values.flatten(), annotator2.values.flatten())
        kappa_scores.append(k)
    mean_kappa = sum(kappa_scores) / len(kappa_scores)

    print ('Il K tra ' + str(annotator_1) +' e ' + str(annotator_2) +' Ã¨  di: '  + str(mean_kappa))
    return mean_kappa

k_manuel_angelo = getKappa('Manuel', 'Angelo')
k_manuel_marinella = getKappa('Manuel', 'Marinella')
k_angelo_marinella = getKappa('Angelo', 'Marinella')

------------------
465    1.625616e+18
Name: Q2.9.2, dtype: float64
466    1.625616e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
598    1.625789e+18
Name: Q2.9.2, dtype: float64
599   -9.223372e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
394   -9.223372e+18
Name: Q2.9.2, dtype: float64
395   -9.223372e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
515   -9.223372e+18
Name: Q2.9.2, dtype: float64
516    1.625098e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
441    1.620864e+18
Name: Q2.9.2, dtype: float64
442   -9.223372e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
570    1.625616e+18
Name: Q2.9.2, dtype: float64
571    1.625616e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
30    1.620518e+18
Name: Q2.9.2, dtype: float64
31    1.620518e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
313   -9.223372e+18
Name: Q2.9.2, dtype: float64
314   -9.223372e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
66    1.620778e+18
Name: Q2.9.2, dtype: float64
67    1.618186e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
414   -9.223372e+18
Name: Q2.9.2, dtype: float64
415    1.622160e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
576   -9.223372e+18
Name: Q2.9.2, dtype: float64
577   -9.223372e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
276   -9.223372e+18
Name: Q2.9.2, dtype: float64
277    1.620778e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
614   -9.223372e+18
Name: Q2.9.2, dtype: float64
615   -9.223372e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
501    1.625443e+18
Name: Q2.9.2, dtype: float64
502    1.625443e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
198    1.619482e+18
Name: Q2.9.2, dtype: float64
199    1.619482e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
503    1.625530e+18
Name: Q2.9.2, dtype: float64
504    1.625530e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
300   -9.223372e+18
Name: Q2.9.2, dtype: float64
301   -9.223372e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
205    1.620778e+18
Name: Q2.9.2, dtype: float64
206    1.620778e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
18    1.619741e+18
Name: Q2.9.2, dtype: float64
19    1.619741e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
282   -9.223372e+18
Name: Q2.9.2, dtype: float64
283   -9.223372e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
485    1.625098e+18
Name: Q2.9.2, dtype: float64
486    1.625184e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
120   -9.223372e+18
Name: Q2.9.2, dtype: float64
121   -9.223372e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
96    1.621728e+18
Name: Q2.9.2, dtype: float64
97    1.622160e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
422   -9.223372e+18
Name: Q2.9.2, dtype: float64
423   -9.223372e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
39   -9.223372e+18
Name: Q2.9.2, dtype: float64
40   -9.223372e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
45   -9.223372e+18
Name: Q2.9.2, dtype: float64
46   -9.223372e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
305    1.613174e+18
Name: Q2.9.2, dtype: float64
306    1.613088e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
556    1.623974e+18
Name: Q2.9.2, dtype: float64
557   -9.223372e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
229    1.620950e+18
Name: Q2.9.2, dtype: float64
230    1.620950e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
519   -9.223372e+18
Name: Q2.9.2, dtype: float64
520   -9.223372e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
153   -9.223372e+18
Name: Q2.9.2, dtype: float64
154   -9.223372e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
434    1.621210e+18
Name: Q2.9.2, dtype: float64
435    1.621210e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
539   -9.223372e+18
Name: Q2.9.2, dtype: float64
541   -9.223372e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
444    1.621382e+18
Name: Q2.9.2, dtype: float64
445    1.621382e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
531    1.625357e+18
Name: Q2.9.2, dtype: float64
532    1.625357e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
137    1.621037e+18
Name: Q2.9.2, dtype: float64
138    1.621037e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
233    1.635725e+18
Name: Q2.9.2, dtype: float64
234    1.636848e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
634   -9.223372e+18
Name: Q2.9.2, dtype: float64
635   -9.223372e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
336    1.620864e+18
Name: Q2.9.2, dtype: float64
337    1.620864e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
241   -9.223372e+18
Name: Q2.9.2, dtype: float64
242   -9.223372e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
356    1.622246e+18
Name: Q2.9.2, dtype: float64
357    1.622246e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
622    1.625357e+18
Name: Q2.9.2, dtype: float64
623    1.625443e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
135    1.622246e+18
Name: Q2.9.2, dtype: float64
136    1.622246e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
47    1.622506e+18
Name: Q2.9.2, dtype: float64
48    1.622419e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
188    1.622419e+18
Name: Q2.9.2, dtype: float64
189    1.622419e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
98   -9.223372e+18
Name: Q2.9.2, dtype: float64
99   -9.223372e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
213    1.622419e+18
Name: Q2.9.2, dtype: float64
214    1.622419e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
578    1.625443e+18
Name: Q2.9.2, dtype: float64
579    1.625443e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
53    1.622333e+18
Name: Q2.9.2, dtype: float64
54    1.622333e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
307    1.622246e+18
Name: Q2.9.2, dtype: float64
308    1.622246e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
360   -9.223372e+18
Name: Q2.9.2, dtype: float64
361   -9.223372e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
102   -9.223372e+18
Name: Q2.9.2, dtype: float64
103   -9.223372e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
398    1.586131e+18
Name: Q2.9.2, dtype: float64
399    1.586131e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
592    1.624838e+18
Name: Q2.9.2, dtype: float64
593    1.624838e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
643    1.624147e+18
Name: Q2.9.2, dtype: float64
644    1.624147e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
12    1.621469e+18
Name: Q2.9.2, dtype: float64
13    1.621469e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
221   -9.223372e+18
Name: Q2.9.2, dtype: float64
222   -9.223372e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
379   -9.223372e+18
Name: Q2.9.2, dtype: float64
380   -9.223372e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
284   -9.223372e+18
Name: Q2.9.2, dtype: float64
285   -9.223372e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
166   -9.223372e+18
Name: Q2.9.2, dtype: float64
167    1.622246e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
537    1.625702e+18
Name: Q2.9.2, dtype: float64
538    1.625702e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
257   -9.223372e+18
Name: Q2.9.2, dtype: float64
258    1.612829e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
192   -9.223372e+18
Name: Q2.9.2, dtype: float64
193   -9.223372e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
180    1.611360e+18
Name: Q2.9.2, dtype: float64
181    1.611360e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
507    1.624925e+18
Name: Q2.9.2, dtype: float64
508    1.625184e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
51   -9.223372e+18
Name: Q2.9.2, dtype: float64
52   -9.223372e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
168    1.625184e+18
Name: Q2.9.2, dtype: float64
169    1.625184e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
194   -9.223372e+18
Name: Q2.9.2, dtype: float64
195   -9.223372e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
454   -9.223372e+18
Name: Q2.9.2, dtype: float64
455    1.625443e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
231   -9.223372e+18
Name: Q2.9.2, dtype: float64
232    1.620778e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
438    1.622333e+18
Name: Q2.9.2, dtype: float64
439    1.622333e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
86    1.610669e+18
Name: Q2.9.2, dtype: float64
87   -9.223372e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
71    1.620432e+18
Name: Q2.9.2, dtype: float64
72    1.601597e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
647    1.623629e+18
Name: Q2.9.2, dtype: float64
648    1.623542e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
568    1.624406e+18
Name: Q2.9.2, dtype: float64
569    1.624925e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
372    1.622419e+18
Name: Q2.9.2, dtype: float64
373    1.622419e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
574    1.625702e+18
Name: Q2.9.2, dtype: float64
575    1.625702e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
237    1.622333e+18
Name: Q2.9.2, dtype: float64
238    1.622333e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
186   -9.223372e+18
Name: Q2.9.2, dtype: float64
187   -9.223372e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
14    1.622506e+18
Name: Q2.9.2, dtype: float64
15    1.625011e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
604   -9.223372e+18
Name: Q2.9.2, dtype: float64
605   -9.223372e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
505    1.624666e+18
Name: Q2.9.2, dtype: float64
506    1.624666e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
628   -9.223372e+18
Name: Q2.9.2, dtype: float64
629   -9.223372e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
521    1.624666e+18
Name: Q2.9.2, dtype: float64
522    1.624666e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
487    1.625443e+18
Name: Q2.9.2, dtype: float64
488    1.625443e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
342   -9.223372e+18
Name: Q2.9.2, dtype: float64
343   -9.223372e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
161    1.622419e+18
Name: Q2.9.2, dtype: float64
162    1.590883e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
249    1.620950e+18
Name: Q2.9.2, dtype: float64
250   -9.223372e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
655    1.625443e+18
Name: Q2.9.2, dtype: float64
656   -9.223372e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
446   -9.223372e+18
Name: Q2.9.2, dtype: float64
447   -9.223372e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
286    1.620346e+18
Name: Q2.9.2, dtype: float64
287    1.620346e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
527    1.625270e+18
Name: Q2.9.2, dtype: float64
528    1.625270e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
452   -9.223372e+18
Name: Q2.9.2, dtype: float64
453    1.625184e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
139    1.621901e+18
Name: Q2.9.2, dtype: float64
140    1.621901e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
362   -9.223372e+18
Name: Q2.9.2, dtype: float64
363   -9.223372e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
60   -9.223372e+18
Name: Q2.9.2, dtype: float64
61   -9.223372e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
0    1.622419e+18
Name: Q2.9.2, dtype: float64
1    1.622419e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
370   -9.223372e+18
Name: Q2.9.2, dtype: float64
371   -9.223372e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
513    1.625011e+18
Name: Q2.9.2, dtype: float64
514   -9.223372e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
590    1.625443e+18
Name: Q2.9.2, dtype: float64
591    1.625443e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
201    1.619827e+18
Name: Q2.9.2, dtype: float64
202    1.619827e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
145    1.620950e+18
Name: Q2.9.2, dtype: float64
146    1.620950e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
368    1.622419e+18
Name: Q2.9.2, dtype: float64
369    1.622074e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
118   -9.223372e+18
Name: Q2.9.2, dtype: float64
119   -9.223372e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
572   -9.223372e+18
Name: Q2.9.2, dtype: float64
573   -9.223372e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
624    1.625011e+18
Name: Q2.9.2, dtype: float64
625    1.625011e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
196    1.620864e+18
Name: Q2.9.2, dtype: float64
197    1.620950e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
128    1.620605e+18
Name: Q2.9.2, dtype: float64
129    1.620605e+18
Name: Q2.9.2, dtype: float64
------------------
Il K tra Manuel e Angelo Ã¨  di: 0.7596847484068775
------------------
130   -9.223372e+18
Name: Q2.9.2, dtype: float64
131   -9.223372e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
122    1.622851e+18
Name: Q2.9.2, dtype: float64
123    1.622851e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
544    1.626653e+18
Name: Q2.9.2, dtype: float64
545    1.626653e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
467    1.625011e+18
Name: Q2.9.2, dtype: float64
468   -9.223372e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
632    1.621037e+18
Name: Q2.9.2, dtype: float64
633    1.621037e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
330    1.620864e+18
Name: Q2.9.2, dtype: float64
331    1.620864e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
450    1.619050e+18
Name: Q2.9.2, dtype: float64
451    1.619050e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
4   -9.223372e+18
Name: Q2.9.2, dtype: float64
5   -9.223372e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
108    1.620864e+18
Name: Q2.9.2, dtype: float64
109    1.620950e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
596   -9.223372e+18
Name: Q2.9.2, dtype: float64
597   -9.223372e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
255    1.622419e+18
Name: Q2.9.2, dtype: float64
256    1.622246e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
164   -9.223372e+18
Name: Q2.9.2, dtype: float64
165   -9.223372e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
580    1.625530e+18
Name: Q2.9.2, dtype: float64
581    1.625530e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
49    1.622419e+18
Name: Q2.9.2, dtype: float64
50    1.622419e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
340    1.621555e+18
Name: Q2.9.2, dtype: float64
341    1.621555e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
243   -9.223372e+18
Name: Q2.9.2, dtype: float64
244   -9.223372e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
251    1.625098e+18
Name: Q2.9.2, dtype: float64
252    1.625098e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
326    1.610669e+18
Name: Q2.9.2, dtype: float64
327    1.610669e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
184   -9.223372e+18
Name: Q2.9.2, dtype: float64
185   -9.223372e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
82   -9.223372e+18
Name: Q2.9.2, dtype: float64
83   -9.223372e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
416    1.620864e+18
Name: Q2.9.2, dtype: float64
417    1.620864e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
584    1.625530e+18
Name: Q2.9.2, dtype: float64
585    1.625530e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
223    1.621123e+18
Name: Q2.9.2, dtype: float64
224    1.621037e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
91    1.621987e+18
Name: Q2.9.2, dtype: float64
92    1.621987e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
209    1.620950e+18
Name: Q2.9.2, dtype: float64
210    1.620950e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
288    1.620173e+18
Name: Q2.9.2, dtype: float64
289    1.620173e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
332    1.622333e+18
Name: Q2.9.2, dtype: float64
333    1.622333e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
24    1.622678e+18
Name: Q2.9.2, dtype: float64
25    1.622333e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
459    1.626826e+18
Name: Q2.9.2, dtype: float64
460    1.626826e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
471    1.625184e+18
Name: Q2.9.2, dtype: float64
472    1.625184e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
377    1.622419e+18
Name: Q2.9.2, dtype: float64
378   -9.223372e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
539   -9.223372e+18
Name: Q2.9.2, dtype: float64
540   -9.223372e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
558   -9.223372e+18
Name: Q2.9.2, dtype: float64
559   -9.223372e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
564    1.624320e+18
Name: Q2.9.2, dtype: float64
565   -9.223372e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
366   -9.223372e+18
Name: Q2.9.2, dtype: float64
367    1.622333e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
430   -9.223372e+18
Name: Q2.9.2, dtype: float64
431   -9.223372e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
586    1.624666e+18
Name: Q2.9.2, dtype: float64
587    1.624666e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
245   -9.223372e+18
Name: Q2.9.2, dtype: float64
246    1.622246e+18
Name: Q2.9.2, dtype: float64
------------------
------------------
28    1.620864e+18
Name: Q2.9.2, dtype: float64
29    1.620864e+18
Name: Q2.9.2, dtype: float64
------------------

https://it.wikipedia.org/wiki/Kappa_di_Cohen#:~:text=se%20k%20assume%20valori%20compresi,1%2C%20la%20concordanza%20%C3%A8%20ottima

se k assume valori compresi tra 0-0,4, allora la concordanza Ã¨ scarsa; se k assume valori compresi tra 0,4-0,6, allora la concordanza Ã¨ discreta; se k assume valori compresi tra 0,6-0,8, la concordanza Ã¨ buona; se k assume valori compresi tra 0,8-1, la concordanza Ã¨ ottima.