In [20]:
import pandas as pd
import numpy as np

df = pd.read_csv('../Annotazioni/Annotazioni_controllate.csv')

df

,id,title,label,annotator,Q.1.1 Type of news,Q.1.2 Accuracy,Q.1.3 Headline,Q1.3.1 Quotation,Q.1.4 Fact-based lead,Q.1.5 Bias,Q.1.6 Sensational language,Q1.7 Negative target,Q2.8 Attribution,Q2.9.1 Date,Q2.10 event 30 days
0,18d71db7-f362-46fa-953e-d8353c7f7232,Coronavirus| nuove regole: al tavolo al ristor...,Group 2,Manuel,0,2,['3'],0,2,0,0,1,1,2,2
1,18d71db7-f362-46fa-953e-d8353c7f7232,Coronavirus| nuove regole: al tavolo al ristor...,Group 2,Marinella,0,0,NaN,0,0,0,0,0,0,0,0
2,18d71db7-f362-46fa-953e-d8353c7f7232,Coronavirus| nuove regole: al tavolo al ristor...,Group 2,Angelo,0,3,"['1', '3']",1,1,0,0,1,1,2,2
3,3ca70f03-38f3-4a7b-bdd3-f012b22e0c7e,Israele: Lapid| ostacoli ma fiducioso su nuovo...,Group 2,Manuel,0,4,"['1', '3']",0,2,0,0,1,3,2,2
4,3ca70f03-38f3-4a7b-bdd3-f012b22e0c7e,Israele: Lapid| ostacoli ma fiducioso su nuovo...,Group 2,Marinella,0,4,"['1', '3']",0,1,0,0,2,3,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1058,5b30e244-4aa2-4ad3-b24a-2022c1415df7,Cosa fare dei documenti della Stasi,Group 1,Marinella,0,3,"['1', '8']",0,1,0,0,1,1,2,2
1059,5b30e244-4aa2-4ad3-b24a-2022c1415df8,Cosa fare dei documenti della Stasi,Group 1,Angelo,0,3,"['1', '9']",0,2,0,0,1,1,2,2
1060,eab45a62-1d47-4216-a51d-e45ccbcc3810,"Strani dolori allo stomaco, dopo 6 mesi muore ...",Group 1,Manuel,0,0,NaN,0,0,0,0,0,0,0,0
1061,eab45a62-1d47-4216-a51d-e45ccbcc3810,"Strani dolori allo stomaco, dopo 6 mesi muore ...",Group 1,Marinella,0,4,"['1', '9']",0,1,0,0,1,3,2,2
1062,eab45a62-1d47-4216-a51d-e45ccbcc3810,"Strani dolori allo stomaco, dopo 6 mesi muore ...",Group 1,Angelo,0,4,"['1', '9']",0,2,0,0,1,3,2,2

In [23]:
from py_agreement import kappa

# Estrai le annotazioni per ogni annotatore
annotations_manuel = df.loc[df['annotator'] == 'Manuel', 'label']
annotations_marinella = df.loc[df['annotator'] == 'Marinella', 'label']
annotations_angelo = df.loc[df['annotator'] == 'Angelo', 'label']

# Calcola il Cohen's Kappa
kappa_value = kappa(annotations_manuel, annotations_marinella)

# Stampa il valore del Kappa
print(kappa_value)

ModuleNotFoundError: No module named 'py_agreement'