In [13]:
import pandas as pd

df = pd.read_csv('../merged_checked.csv')

df

,id,title,label,annotator,Q1.1,Q1.2,Q1.3,Q1.3.1,Q1.4,Q1.5,Q1.6,Q1.7,Q1.7.1,Q1.7.1.2,Q2.8,Q2.9.1,Q2.9.2,Q2.10
0,18d71db7-f362-46fa-953e-d8353c7f7232,Coronavirus| nuove regole: al tavolo al ristor...,Group 2,Manuel,1,2,31,-1,2,4,4,1,0,-1,1,2,2021-05-31,2
1,18d71db7-f362-46fa-953e-d8353c7f7232,Coronavirus| nuove regole: al tavolo al ristor...,Group 2,Angelo,1,3,10,1,1,4,4,1,0,-1,1,2,2021-05-31,2
2,3ca70f03-38f3-4a7b-bdd3-f012b22e0c7e,Israele: Lapid| ostacoli ma fiducioso su nuovo...,Group 2,Manuel,1,4,10,-1,2,4,4,1,0,-1,3,2,2021-05-31,2
3,3ca70f03-38f3-4a7b-bdd3-f012b22e0c7e,Israele: Lapid| ostacoli ma fiducioso su nuovo...,Group 2,Marinella,1,4,10,-1,1,4,4,2,5,-1,3,2,2021-05-31,2
4,34b92f4c-32db-454c-a369-ca2032443f6c,Le borsette fatte a 3 euro l'ora vendute a 820...,Group 1,Manuel,2,3,31,-1,1,3,2,2,5,Fashion craft industries system,3,1,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
663,b0e8474a-3d81-4e6e-b9a7-8dcf5e2bccd9,"Regno Unito, giornalista BBC muore a 44 anni d...",NaN,ChatGPT4AsAnnotator,5,4,3,-1,2,4,4,2,2,-1,3,2,NaN,2
664,50949429-a643-421e-a7ae-edb78fe8f0ab,Cvc conquista la multinazionale della consulen...,NaN,ChatGPT4AsAnnotator,1,4,0,-1,2,4,4,1,0,-1,3,2,NaN,2
665,a223ad9c-9cc2-4e23-80fa-cb3bbba183da,"D'Alema ""rovinato"". Ma lui reagisce così: ""Ven...",NaN,ChatGPT4AsAnnotator,1,4,0,-1,2,3,3,2,1,-1,3,2,NaN,2
666,c0093d33-ac00-44c3-9616-286506ce87c0,La sanità del futuro parte dal territorio,NaN,ChatGPT4AsAnnotator,2,4,0,-1,2,4,3,1,0,-1,3,2,NaN,1
667,d7137589-65e6-426a-9f91-4fa2497b51c7,"Ex Ilva: sentenza, 22 e 20 anni a Fabio e Nico...",NaN,ChatGPT4AsAnnotator,1,4,0,-1,2,4,4,2,1,-1,3,2,NaN,1

In [14]:
# Selezione delle righe
subset_annotator_manuel_Q1_1 = df[(df['annotator'] == 'Manuel') & (df['Q1.1'] == 3)]
subset_chatgpt_annotator_Q1_1 = df[(df['annotator'] == 'ChatGPT4AsAnnotator') & (df['Q1.1'] == 1)]

# Selezione delle righe con lo stesso id
ids_to_select = subset_annotator_manuel_Q1_1['id'].unique()
final_subset = subset_chatgpt_annotator_Q1_1[subset_chatgpt_annotator_Q1_1['id'].isin(ids_to_select)]

final_subset.to_csv('1.1_test.csv')

In [15]:
# Selezione delle righe
subset_annotator_manuel_Q1_1 = df[(df['annotator'] == 'Manuel') & (df['Q1.3.1'] == 1)]
subset_chatgpt_annotator_Q1_1 = df[(df['annotator'] == 'ChatGPT4AsAnnotator') & (df['Q1.3.1'] == 2)]

# Selezione delle righe con lo stesso id
ids_to_select = subset_annotator_manuel_Q1_1['id'].unique()
final_subset = subset_chatgpt_annotator_Q1_1[subset_chatgpt_annotator_Q1_1['id'].isin(ids_to_select)]

final_subset.to_csv('1.3.1_test.csv')

In [16]:
# Filtra gli articoli annotati sia da Manuel che da ChatGPT4AsAnnotator
df = df[
    (df['annotator'] == 'Manuel') | 
    (df['annotator'] == 'ChatGPT4AsAnnotator')
]
df


# Conta quante volte appare ciascun articolo
article_counts = df['id'].value_counts()

# Filtra il DataFrame mantenendo solo le righe degli articoli che compaiono esattamente due volte
df = df[df['id'].isin(article_counts[article_counts == 2].index)]

# Ora df_filtered contiene solo le righe degli articoli che compaiono due volte
print(df)

                                       id  \
95   3b09cd47-b33c-4b83-a07a-c296a878412f
112  47970d6e-a9e8-4eba-b589-35dc3158d5b3
144  c0093d33-ac00-44c3-9616-286506ce87c0
179  50949429-a643-421e-a7ae-edb78fe8f0ab
211  ad170310-dae8-4616-90fa-8817e32bb699
228  ae56883f-1033-44e1-8f06-5e2269ecb793
303  7394a8e4-0fc9-4efc-a379-6b5e7efa0675
326  b0e8474a-3d81-4e6e-b9a7-8dcf5e2bccd9
339  f449f8f5-f4d6-40f6-a573-89e9837cd6af
346  a223ad9c-9cc2-4e23-80fa-cb3bbba183da
354  4b7f561b-a4bc-4cdb-8722-1450f1ce7c38
356  7b64542e-11d0-464d-a060-1145a9d0ad3a
476  af6c349c-3ed8-4afb-b31a-411cfd2f212d
480  f620ad74-b7b2-4269-b02e-af033a2f04b2
502  3d1ae696-3a3f-43ab-a4ce-61d337a59d7e
535  d73018e2-5184-43b7-ba01-e82378666dab
557  1d134854-568a-4590-86b1-64912b3c3e4d
593  72ab85c4-04fa-44ed-b4ae-5f570db46aab
641  3d1ae696-3a3f-43ab-a4ce-61d337a59d7e
642  7b64542e-11d0-464d-a060-1145a9d0ad3a
643  d73018e2-5184-43b7-ba01-e82378666dab
644  1d134854-568a-4590-86b1-64912b3c3e4d
645  47970d6e-a9e8-4eba-b589-35dc3158d5b3
648  f449f8f5-f4d6-40f6-a573-89e9837cd6af
649  72ab85c4-04fa-44ed-b4ae-5f570db46aab
650  af6c349c-3ed8-4afb-b31a-411cfd2f212d
654  3b09cd47-b33c-4b83-a07a-c296a878412f
658  f620ad74-b7b2-4269-b02e-af033a2f04b2
659  4b7f561b-a4bc-4cdb-8722-1450f1ce7c38
660  ae56883f-1033-44e1-8f06-5e2269ecb793
661  ad170310-dae8-4616-90fa-8817e32bb699
662  7394a8e4-0fc9-4efc-a379-6b5e7efa0675
663  b0e8474a-3d81-4e6e-b9a7-8dcf5e2bccd9
664  50949429-a643-421e-a7ae-edb78fe8f0ab
665  a223ad9c-9cc2-4e23-80fa-cb3bbba183da
666  c0093d33-ac00-44c3-9616-286506ce87c0

                                                 title    label  \
95   «Conte| la verità è un’altra: l’Inter non lo v...  Group 2
112  Covid| specializzanda del Policlinico di Bari:...  Group 2
144          La sanità del futuro parte dal territorio  Group 2
179  Cvc conquista la multinazionale della consulen...  Group 2
211  A Cassaro 100% di vaccinati: è il primo Comune...  Group 2
228  «Se sono ubriaca e ci provi| non è un gesto d'...  Group 2
303  Ema autorizza il vaccino Pfizer per i 12-15enn...  Group 2
326  Regno Unito| giornalista BBC muore a 44 anni d...  Group 2
339  Il virus rallenta ancora. Tre regioni in zona ...  Group 2
346  D'Alema "rovinato". Ma lui reagisce così: "Ven...  Group 1
354  La Fondazione farà crescere i Giganti di Mont'...  Group 2
356  Il premier libico a Roma| dalla ricostruzione ...  Group 2
476  Covid Italia| vaccini: "Affrettarsi prima dell...  Group 2
480  Ora il turismo extra-Unione europea fa paura. ...  Group 2
502  Strage nel Mediterraneo: barcone si ribalta| m...  Group 2
535  In Fvg trovata la variante Delta in 25 dei 96 ...  Group 2
557  Nuove aggressioni omofobe a Milano: calci e pu...  Group 2
593  Papa Francesco operato per "stenosi diverticol...  Group 1
641  Strage nel Mediterraneo: barcone si ribalta, m...      NaN
642  Il premier libico a Roma, dalla ricostruzione ...      NaN
643  In Fvg trovata la variante Delta in 25 dei 96 ...      NaN
644  Nuove aggressioni omofobe a Milano: calci e pu...      NaN
645  Covid, specializzanda del Policlinico di Bari:...      NaN
648  Il virus rallenta ancora. Tre regioni in zona ...      NaN
649  Papa Francesco operato per "stenosi diverticol...      NaN
650  Covid Italia, vaccini: "Affrettarsi prima dell...      NaN
654  «Conte, la verità è un’altra: l’Inter non lo v...      NaN
658  Ora il turismo extra-Unione europea fa paura. ...      NaN
659  La Fondazione farà crescere i Giganti di Mont'...      NaN
660  «Se sono ubriaca e ci provi, non è un gesto d'...      NaN
661  A Cassaro 100% di vaccinati: è il primo Comune...      NaN
662  Ema autorizza il vaccino Pfizer per i 12-15enn...      NaN
663  Regno Unito, giornalista BBC muore a 44 anni d...      NaN
664  Cvc conquista la multinazionale della consulen...      NaN
665  D'Alema "rovinato". Ma lui reagisce così: "Ven...      NaN
666          La sanità del futuro parte dal territorio      NaN

               annotator  Q1.1  Q1.2  Q1.3  Q1.3.1  Q1.4  Q1.5  Q1.6  Q1.7  \
95                Manuel     3     3    11       1     1     4     4     1
112               Manuel     1     4    11       2     1     4     4     1
144               Manuel     2     2     0      -1     1     4     3     1
179               Manuel     1     3     0      -1     2     4     4     1
211               Manuel     1     4    10      -1     1     4     4     1
228               Manuel     3     2    14       1     1     4     4     1
303               Manuel     1     3     1      -1     2     4     4     1
326               Manuel     1     4     1      -1     2     3     4     1
339               Manuel     1     4     0      -1     2     4     4     1
346               Manuel     1     2    14       1     2     4     4     1
354               Manuel     3     2     1      -1     1     4     3     1
356               Manuel     3     4    10      -1     1     4     4     1
476               Manuel     1     3    11       2     1     4     4     1
480               Manuel     1     3    28      -1     2     4     4     1
502               Manuel     1     4    10      -1     2     4     4     1
535               Manuel     1     3    11       1     1     4     4     1
557               Manuel     1     4    10      -1     2     4     4     1
593               Manuel     1     3    14       1     2     3     4     1
641  ChatGPT4AsAnnotator     1     4     0      -1     2     4     3     1
642  ChatGPT4AsAnnotator     1     4     0      -1     2     4     3     1
643  ChatGPT4AsAnnotator     1     4     0      -1     2     4     4     1
644  ChatGPT4AsAnnotator     1     4     0      -1     2     4     3     2
645  ChatGPT4AsAnnotator     5     4     3      -1     2     4     4     2
648  ChatGPT4AsAnnotator     1     4     0      -1     2     4     4     1
649  ChatGPT4AsAnnotator     5     4     3      -1     2     4     4     2
650  ChatGPT4AsAnnotator     3     4     0      -1     2     4     3     1
654  ChatGPT4AsAnnotator     2     4     2      -1     1     2     2     2
658  ChatGPT4AsAnnotator     1     4     0      -1     2     4     3     1
659  ChatGPT4AsAnnotator     2     4     0      -1     2     4     4     1
660  ChatGPT4AsAnnotator     5     4     3      -1     2     4     4     2
661  ChatGPT4AsAnnotator     5     4     3      -1     2     4     4     2
662  ChatGPT4AsAnnotator     3     4     0      -1     2     4     4     1
663  ChatGPT4AsAnnotator     5     4     3      -1     2     4     4     2
664  ChatGPT4AsAnnotator     1     4     0      -1     2     4     4     1
665  ChatGPT4AsAnnotator     1     4     0      -1     2     3     3     2
666  ChatGPT4AsAnnotator     2     4     0      -1     2     4     3     1

     Q1.7.1 Q1.7.1.2  Q2.8  Q2.9.1      Q2.9.2  Q2.10
95        0       -1     3       1         NaN      2
112       0       -1     1       1         NaN      2
144       0       -1     3       1         NaN      2
179       0       -1     3       2  2021-05-31      2
211       0       -1     1       2  2021-05-16      2
228       0       -1     3       1         NaN      1
303       0       -1     1       2  2021-05-28      2
326       0       -1     1       2  2021-05-21      2
339       0       -1     3       2  2021-05-27      2
346       0       -1     3       1         NaN      2
354       0       -1     3       1         NaN      2
356       0       -1     3       2  2021-05-31      2
476       0       -1     1       2  2021-07-05      2
480       0       -1     3       2  2021-06-26      2
502       0       -1     1       2  2021-07-03      2
535       0       -1     1       2  2021-06-22      2
557       0       -1     3       2  2021-06-26      2
593       0       -1     1       2  2021-07-04      2
641       0       -1     3       2  2021-07-03      1
642       0       -1     3       2         NaN      2
643       0       -1     3       2         NaN      1
644       3       -1     3       2         NaN      1
645       0       -1     3       2         NaN      2
648       0       -1     3       2         NaN      2
649       0       -1     3       2         NaN      2
650       0       -1     3       2  2021-07-05      1
654       1   manner     1       2         NaN      2
658       0       -1     1       2         NaN      2
659       0       -1     3       2         NaN      1
660       2       -1     3       2         NaN      2
661       0       -1     3       2         NaN      2
662       0       -1     3       2  2021-05-28      1
663       2       -1     3       2         NaN      2
664       0       -1     3       2         NaN      2
665       1       -1     3       2         NaN      2
666       0       -1     3       2         NaN      1

In [18]:
print('Manuel')
manuel = df[df["annotator"] == "Manuel"]
print(manuel['Q1.1'].value_counts())

print('---------------------------')
print('---------------------------')

gpt = df[df["annotator"] == "ChatGPT4AsAnnotator"]
print('ChatGPT')
print(gpt['Q1.1'].value_counts())

Manuel
Q1.1
1    13
3     4
2     1
Name: count, dtype: int64
---------------------------
---------------------------
ChatGPT
Q1.1
1    8
5    5
2    3
3    2
Name: count, dtype: int64

In [8]:
import json

# La stringa fornita
stringa = """
Q1.1: 1.  Straight news, or 'hard news'
Q1.2: 4.  Extremely accurately
Q1.3: 1.  A proper noun
Q1.3.1: -1. No quotation present
Q1.4: 2.  Yes
Q1.5: 4.  Entirely unbiased
Q1.6: 3.  Mainly neutral
Q1.7: 1.  No
Q2.8: 3.  There is a full name for the author/authors and/or the specific newswire service name
Q2.9.1: 2.  Yes
Q2.9.2: 14/06/2021
Q2.10: 1.  No
"""

# Dividere la stringa in righe e rimuovere eventuali spazi bianchi in eccesso
righe = [line.strip() for line in stringa.split('\n') if line.strip()]

# Inizializzare un dizionario per contenere i dati
dati = {}

# Iterare sulle righe estrarre le chiavi e i valori
for riga in righe:
    chiave, valore = riga.split(':')
    chiave = chiave.strip().replace(' ', ',')  # Modifica il formato della chiave
    valore = valore.split('.')[0].strip()  # Ottieni solo il numero della risposta
    dati[chiave] = valore

# JSON risultante
json_string = json.dumps(dati, indent=4)
print(json_string)

{
    "Q1.1": "1",
    "Q1.2": "4",
    "Q1.3": "1",
    "Q1.3.1": "-1",
    "Q1.4": "2",
    "Q1.5": "4",
    "Q1.6": "3",
    "Q1.7": "1",
    "Q2.8": "3",
    "Q2.9.1": "2",
    "Q2.9.2": "14/06/2021",
    "Q2.10": "1"
}

In [9]:
import json

def stringa_to_json(stringa):
    # Dividere la stringa in righe e rimuovere eventuali spazi bianchi in eccesso
    righe = [line.strip() for line in stringa.split('\n') if line.strip()]

    # Inizializzare un dizionario per contenere i dati
    dati = {}

    # Iterare sulle righe estrarre le chiavi e i valori
    for riga in righe:
        chiave, valore = riga.split(':')
        chiave = chiave.strip().replace(' ', ',')  # Modifica il formato della chiave
        valore = valore.split('.')[0].strip()  # Ottieni solo il numero della risposta
        dati[chiave] = valore

    # JSON risultante
    json_string = json.dumps(dati, indent=4)
    return json_string

# Esempio di utilizzo della funzione
stringa = """
Q1.1: 1.  Straight news, or 'hard news'
Q1.2: 4.  Extremely accurately
Q1.3: 1.  A proper noun
Q1.3.1: -1. No quotation present
Q1.4: 2.  Yes
Q1.5: 4.  Entirely unbiased
Q1.6: 3.  Mainly neutral
Q1.7: 1.  No
Q2.8: 3.  There is a full name for the author/authors and/or the specific newswire service name
Q2.9.1: 2.  Yes
Q2.9.2: 14/06/2021
Q2.10: 1.  No
"""

json_result = stringa_to_json(stringa)
print(json_result)

{
    "Q1.1": "1",
    "Q1.2": "4",
    "Q1.3": "1",
    "Q1.3.1": "-1",
    "Q1.4": "2",
    "Q1.5": "4",
    "Q1.6": "3",
    "Q1.7": "1",
    "Q2.8": "3",
    "Q2.9.1": "2",
    "Q2.9.2": "14/06/2021",
    "Q2.10": "1"
}

In [12]:
import json

def stringa_to_json(stringa):
    # Dividere la stringa in righe e rimuovere eventuali spazi bianchi in eccesso
    righe = [line.strip() for line in stringa.split('\n') if line.strip()]

    # Inizializzare un dizionario per contenere i dati
    dati = {}

    # Variabile per tenere traccia della chiave corrente
    current_key = None

    # Iterare sulle righe estrarre le chiavi e i valori
    for riga in righe:
        # Se la riga inizia con "Q", allora è una nuova chiave
        if riga.startswith("Q"):
            current_key = riga.split(" ")[0].replace(':', ',')
            dati[current_key] = {}
        # Altrimenti, se la riga non inizia con "Q" e c'è una chiave corrente, allora è una risposta
        elif current_key:
            valore = riga.split(".")[0].strip().split()[-1]
            dati[current_key] = valore

    # JSON risultante
    json_string = json.dumps(dati, indent=4)
    return json_string

# Esempio di utilizzo della funzione
stringa = """
Q1.1 What type of news article are you reviewing? (Check one):
    1.  Straight news, or 'hard news'

Q1.2: How accurately does the story’s headline describe the content of the story? (Check one):
    4.  Extremely accurately

Q1.3: Does the story’s headline contain any of the following elements? (Check all that apply):
    1.  A proper noun

Q1.3.1: If the headline contains a quotation, does that same quotation appear in the content of the story? (Check one):
    -1. No quotation present

Q1.4: Does the article begin with a fact-based lead? (Check one):
    2.  Yes

Q1.5 Please rate the degree of bias in the article copy (Check one):
    4.  Entirely unbiased

Q1.6 Does the article use sensationalised language? (Check one):
    3.  Mainly neutral

Q1.7 Does this story negatively target a specific group or individual? (Check one):
    1.  No

Q2.8 How much information is provided in the article’s byline? 
    3.  There is a full name for the author/authors and/or the specific newswire service name

Q2.9.1 Can you determine the date of the event covered by the article? (Check one):
    2.  Yes

Q2.9.2 If the answer to Q2.9.1 is yes (2. Yes), enter the date of the event being reported (DD/MM/YYYY):
    03/07/2021

Q2.10 Is the story covering a news event or development that occurred within 30 days prior to the article’s publication date? (Check one):
    1.  No
"""

json_result = stringa_to_json(stringa)
print(json_result)

{
    "Q1.1": "1",
    "Q1.2,": "4",
    "Q1.3,": "1",
    "Q1.3.1,": "-1",
    "Q1.4,": "2",
    "Q1.5": "4",
    "Q1.6": "3",
    "Q1.7": "1",
    "Q2.8": "3",
    "Q2.9.1": "2",
    "Q2.9.2": "03/07/2021",
    "Q2.10": "1"
}