In [10]:
import pandas as pd

df = pd.read_csv('../merged_checked.csv')

df

,id,title,label,annotator,Q1.1,Q1.2,Q1.3,Q1.3.1,Q1.4,Q1.5,Q1.6,Q1.7,Q1.7.1,Q1.7.1.2,Q2.8,Q2.9.1,Q2.9.2,Q2.10
0,18d71db7-f362-46fa-953e-d8353c7f7232,Coronavirus| nuove regole: al tavolo al ristor...,Group 2,Manuel,1,2,3,-1,2,4,4,1,-1,-1,1,2,2021-05-31,2
1,18d71db7-f362-46fa-953e-d8353c7f7232,Coronavirus| nuove regole: al tavolo al ristor...,Group 2,Angelo,1,3,1;3,1,1,4,4,1,-1,-1,1,2,2021-05-31,2
2,3ca70f03-38f3-4a7b-bdd3-f012b22e0c7e,Israele: Lapid| ostacoli ma fiducioso su nuovo...,Group 2,Manuel,1,4,1;3,-1,2,4,4,1,-1,-1,3,2,2021-05-31,2
3,3ca70f03-38f3-4a7b-bdd3-f012b22e0c7e,Israele: Lapid| ostacoli ma fiducioso su nuovo...,Group 2,Marinella,1,4,1;3,-1,1,4,4,2,11,-1,3,2,2021-05-31,2
4,34b92f4c-32db-454c-a369-ca2032443f6c,Le borsette fatte a 3 euro l'ora vendute a 820...,Group 1,Manuel,2,3,3,-1,1,3,2,2,11,Fashion craft industries system,3,1,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1010,95357073-ff48-47ab-a0ad-62324150033a,L’imprenditore che produce monoclonali a Latin...,Group 1,ChatGPT4AsAnnotator,3,4,1,2,2,3,3,1,-1,-1,3,2,2021-02-01,2
1011,d30b11b6-a665-438c-8ee2-12ea175daeb5,"I nuovi colori da lunedì 17 maggio, l’ordinanz...",Group 1,ChatGPT4AsAnnotator,1,4,1,2,2,4,3,1,NaN,-1,3,2,2021-05-17,2
1012,abe99528-6405-4ebb-9b2f-2e76fb08ac53,Anche le Carresi inseguono la Zona Bianca,Group 2,ChatGPT4AsAnnotator,3,4,1,2,2,4,3,1,-1,-1,3,2,NaN,1
1013,8633735e-f183-4d8e-a1e7-9d49b1a2a7b4,Le stoccate di Draghi per infilzare Conte,Group 1,ChatGPT4AsAnnotator,2,4,1,2,2,2,2,2,11,Giuseppe Conte,3,2,NaN,1
1014,23bae5d9-64ee-46b3-b479-ebd24f5f4a98,"Natalità. Assegni generosi, congedi e servizi....",Group 1,ChatGPT4AsAnnotator,3,4,1,2,2,4,3,1,-1,-1,3,2,NaN,1

In [13]:
test = df.loc[df['Q1.4'] == 1]

In [14]:
test

,id,title,label,annotator,Q1.1,Q1.2,Q1.3,Q1.3.1,Q1.4,Q1.5,Q1.6,Q1.7,Q1.7.1,Q1.7.1.2,Q2.8,Q2.9.1,Q2.9.2,Q2.10
1,18d71db7-f362-46fa-953e-d8353c7f7232,Coronavirus| nuove regole: al tavolo al ristor...,Group 2,Angelo,1,3,1;3,1,1,4,4,1,-1,-1,1,2,2021-05-31,2
3,3ca70f03-38f3-4a7b-bdd3-f012b22e0c7e,Israele: Lapid| ostacoli ma fiducioso su nuovo...,Group 2,Marinella,1,4,1;3,-1,1,4,4,2,11,-1,3,2,2021-05-31,2
4,34b92f4c-32db-454c-a369-ca2032443f6c,Le borsette fatte a 3 euro l'ora vendute a 820...,Group 1,Manuel,2,3,3,-1,1,3,2,2,11,Fashion craft industries system,3,1,NaN,1
5,34b92f4c-32db-454c-a369-ca2032443f6c,Le borsette fatte a 3 euro l'ora vendute a 820...,Group 1,Marinella,2,3,3;9,-1,1,3,2,2,11,Mass production,3,1,NaN,1
7,3ca3093a-5786-4c90-8891-1bba8f8ba160,Il ministro: Vaccini anche in vacanza. In futu...,Group 2,Angelo,1,3,1;3,1,1,4,4,1,-1,-1,1,1,NaN,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
666,44ac5edd-4db4-45e6-ba35-5300bf509f5a,"Il successo dei Pro Gamer, i nuovi campioni",-1,Marinella,3,3,1,-1,1,4,4,1,-1,-1,1,1,NaN,1
667,44ac5edd-4db4-45e6-ba35-5300bf509f5a,"Il successo dei Pro Gamer, i nuovi campioni",-1,Angelo,3,2,9,-1,1,4,4,1,-1,-1,1,1,NaN,1
668,ec3a0585-9da6-4732-bf58-c6e659d8e58e,La grande ondata di caldo nel Nord America,Group 1,Marinella,1,3,1,-1,1,4,4,1,-1,-1,1,2,2021-06-30,2
670,5b30e244-4aa2-4ad3-b24a-2022c1415df7,Cosa fare dei documenti della Stasi,Group 1,Marinella,3,3,1;8,-1,1,4,4,1,-1,-1,1,2,2021-06-17,2
672,eab45a62-1d47-4216-a51d-e45ccbcc3810,"Strani dolori allo stomaco, dopo 6 mesi muore ...",Group 1,Marinella,1,4,1;9,-1,1,4,3,1,-1,-1,3,2,2021-06-25,2

In [2]:
an_manuel = df.loc[df["annotator"]=="Manuel"]
an_chatgpt = df.loc[df["annotator"]=="ChatGPT4AsAnnotator"]

id_diff_resp = pd.merge(
    an_manuel,
    an_chatgpt,
    how="left",
    left_on="id",
    right_on="id",
    validate="one_to_one"
)

In [3]:
id_diff_resp = id_diff_resp.loc[id_diff_resp["annotator_y"].notnull()]

In [4]:
id_diff_resp

,id,title_x,label_x,annotator_x,Q1.1_x,Q1.2_x,Q1.3_x,Q1.3.1_x,Q1.4_x,Q1.5_x,...,Q1.4_y,Q1.5_y,Q1.6_y,Q1.7_y,Q1.7.1_y,Q1.7.1.2_y,Q2.8_y,Q2.9.1_y,Q2.9.2_y,Q2.10_y
0,18d71db7-f362-46fa-953e-d8353c7f7232,Coronavirus| nuove regole: al tavolo al ristor...,Group 2,Manuel,1,2,3,-1,2,4,...,2.0,4.0,3.0,1.0,-1,-1,3.0,2.0,NaN,2.0
2,34b92f4c-32db-454c-a369-ca2032443f6c,Le borsette fatte a 3 euro l'ora vendute a 820...,Group 1,Manuel,2,3,3,-1,1,3,...,2.0,3.0,2.0,2.0,10,Pelletteria Serena di Poggio a Caiano,3.0,2.0,2021-05-25,1.0
3,1e96c067-412e-4a93-9dc3-2838ef233942,Caso Ciro Grillo| i video e quella telefonata ...,Group 1,Manuel,1,3,1;4,2,2,4,...,2.0,3.0,3.0,2.0,9,"Silvia, a 19-year-old girl",3.0,2.0,2019-07-17,1.0
4,0c834cb0-392a-4a5e-948f-237a2c8bef31,La madre della neonata salvata in mare: «Chied...,Group 2,Manuel,2,3,4;9,2,2,3,...,2.0,4.0,3.0,2.0,4;9,"Immigrants, Race/ethnicity",3.0,2.0,NaN,2.0
5,184a4635-a693-4ccd-af1a-143455c391e1,Finanziaria: almeno 150 milioni nella variazio...,Group 2,Manuel,1,4,3,-1,2,4,...,2.0,4.0,3.0,1.0,NaN,-1,3.0,2.0,2021-05-31,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222,6ede1205-d74f-4bb1-8c37-15fc5b4738ac,Il degrado di Milano oltre i limiti di guardia,Group 1,Manuel,2,3,1,-1,1,2,...,2.0,2.0,2.0,2.0,1;9,"Liberals, Race/ethnicity",3.0,2.0,NaN,2.0
223,0dc73a1c-4c03-4b2f-8344-f3c898900c01,Habemus Papam,Group 1,Manuel,2,2,9,-1,1,2,...,2.0,2.0,2.0,2.0,3;7,"LGBTQ, Christians/Christianity",1.0,2.0,NaN,1.0
224,cb932977-03e8-46fd-bd91-34e28dba01bd,Il Cts cambia idea suAstrazeneca.Ormai è chiar...,Group 2,Manuel,2,2,1;3,-1,1,2,...,2.0,2.0,2.0,2.0,11,RobertoSperanza,3.0,2.0,NaN,2.0
226,2e46bc4c-a4bb-4d18-ab2b-94dc738db629,I chiusuristi tifano per l’emergenza continua,Group 2,Manuel,3,2,9,-1,1,2,...,2.0,3.0,2.0,2.0,0;1,"Francesco Boccia, Matteo Salvini, Giorgia Meloni",3.0,2.0,2021-07-31,2.0
227,3dba1506-79ad-4986-8e89-8af3ace87096,Enrichetto si schianta sulla legge Lgbt e l’al...,Group 1,Manuel,2,3,1;9,-1,1,2,...,2.0,2.0,2.0,2.0,11,Matteo Renzi,3.0,2.0,NaN,1.0

In [5]:
id_diff_resp.info()

<class 'pandas.core.frame.DataFrame'>
Index: 216 entries, 0 to 227
Data columns (total 35 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           216 non-null    object
 1   title_x      216 non-null    object
 2   label_x      216 non-null    object
 3   annotator_x  216 non-null    object
 4   Q1.1_x       216 non-null    int64
 5   Q1.2_x       216 non-null    int64
 6   Q1.3_x       216 non-null    object
 7   Q1.3.1_x     216 non-null    int64
 8   Q1.4_x       216 non-null    int64
 9   Q1.5_x       216 non-null    int64
 10  Q1.6_x       216 non-null    int64
 11  Q1.7_x       216 non-null    int64
 12  Q1.7.1_x     216 non-null    object
 13  Q1.7.1.2_x   216 non-null    object
 14  Q2.8_x       216 non-null    int64
 15  Q2.9.1_x     216 non-null    int64
 16  Q2.9.2_x     141 non-null    object
 17  Q2.10_x      216 non-null    int64
 18  title_y      216 non-null    object
 19  label_y      216 non-null    object
 20  annotator_y  216 non-null    object
 21  Q1.1_y       216 non-null    float64
 22  Q1.2_y       216 non-null    float64
 23  Q1.3_y       216 non-null    object
 24  Q1.3.1_y     216 non-null    float64
 25  Q1.4_y       216 non-null    float64
 26  Q1.5_y       216 non-null    float64
 27  Q1.6_y       216 non-null    float64
 28  Q1.7_y       216 non-null    float64
 29  Q1.7.1_y     171 non-null    object
 30  Q1.7.1.2_y   216 non-null    object
 31  Q2.8_y       216 non-null    float64
 32  Q2.9.1_y     216 non-null    float64
 33  Q2.9.2_y     119 non-null    object
 34  Q2.10_y      216 non-null    float64
dtypes: float64(10), int64(10), object(15)
memory usage: 60.8+ KB

In [6]:
temp = id_diff_resp.loc[id_diff_resp["Q1.3_x"]!=id_diff_resp["Q1.3_y"]][["id", "annotator_x", "Q1.3_x", "annotator_y", "Q1.3_y", "title_x"]]
# temp = id_diff_resp.loc[(id_diff_resp["Q1.2_x"]!=id_diff_resp["Q1.2_y"]) & 
#                         (id_diff_resp["Q1.1_x"]!=id_diff_resp["Q1.1_y"]) & 
#                         (id_diff_resp["Q1.3.1_x"]!=id_diff_resp["Q1.3.1_y"]) &
#                         (id_diff_resp["Q1.4_x"]!=id_diff_resp["Q1.4_y"]) &
#                         (id_diff_resp["Q1.5_x"]!=id_diff_resp["Q1.5_y"]) &
#                         (id_diff_resp["Q1.6_x"]!=id_diff_resp["Q1.6_y"]) &
#                         (id_diff_resp["Q1.7_x"]!=id_diff_resp["Q1.7_y"])
#                         ][["id", "annotator_x", "Q1.2_x", "annotator_y", "Q1.2_y", "title_x"]]

temp.to_csv('export.csv')